CREATE TABLE [CLO].[AggregatedPosition]
(
Id bigint identity(1,1),
[PositionDateId] int,
[CLO1NumExposure] numeric (32,4),
[CLO2NumExposure] numeric (32,4),
[CLO3NumExposure] numeric (32,4),
[CLO4NumExposure] numeric (32,4),
[CLO5NumExposure] numeric (32,4),
[CLO6NumExposure] numeric (32,4),
[CLO7NumExposure] numeric (32,4),
[CLO1Exposure] varchar(50),
[CLO2Exposure] varchar(50),
[CLO3Exposure] varchar(50),
[CLO4Exposure] varchar(50),
[CLO5Exposure] varchar(50),
[CLO6Exposure] varchar(50),
[CLO7Exposure] varchar(50),
[CLO1PctExposure]  varchar(50),
[CLO2PctExposure]  varchar(50),
[CLO3PctExposure]  varchar(50),
[CLO4PctExposure]  varchar(50),
[CLO5PctExposure]  varchar(50),
[CLO6PctExposure]  varchar(50),
[CLO7PctExposure]  varchar(50),
[CLO1TargetPar]  numeric (32,4),
[CLO2TargetPar]  numeric (32,4),
[CLO3TargetPar]  numeric (32,4),
[CLO4TargetPar]  numeric (32,4),
[CLO5TargetPar]  numeric (32,4),
[CLO6TargetPar]  numeric (32,4),
[CLO7TargetPar]  numeric (32,4),
[SecurityId] INT NOT NULL,
[SecurityCode]   varchar(100),
[SecurityDesc]   varchar(1000),
[BBGId]			 varchar(1000),
[Issuer]		  varchar(1000),
[IssuerId]		int	,
[IssuerDesc]	  varchar(1000),
[Facility] varchar(1000),
[CallDate] varchar(20),
[CountryDesc] varchar(50),
[MaturityDate] varchar(20),
[SnpIndustry] varchar(1000),
[MoodyIndustry] varchar(1000),
[IsCovLite] int,
[IsFloating] varchar(50),
[LienType] varchar(50),
[IsOnWatch] BIT,
[WatchObjectTypeId] smallint,
[WatchObjectId] int,
[WatchId] int,
[WatchComments] varchar(500),
[WatchLastUpdatedOn] varchar(50),
[WatchUser] varchar(1000),
[SellCandidateObjectTypeId] smallint,
[SellCandidateObjectId] int,
[SellCandidateId] int,
[SellCandidateComments] varchar(500),
[SellCandidateLastUpdatedOn] varchar(50),
[SellCandidateUser] varchar(1000),
[OrigSecurityCode] varchar(1000),
[OrigSecurityDesc] varchar(1000),
[OrigBBGId] varchar(1000),
[OrigIssuer] varchar(1000),
[OrigFacility] varchar(1000),
[OrigCallDate] varchar(50),
[OrigMaturityDate] varchar(1000),
[OrigSnpIndustry] varchar(1000),
[OrigMoodyIndustry] varchar(1000),
[OrigIsFloating] varchar(50),
[OrigLienType] varchar(1000),
[OrigMoodyFacilityRatingAdjusted] varchar(1000),
[OrigMoodyCashFlowRatingAdjusted] varchar(1000),
[Bid] varchar(1000),
[Offer] varchar(1000),
[BidNum] numeric (32,4),
[OfferNum] numeric (32,4),
[Spread] numeric(28,2),
[LiborFloor] numeric(28,2),
[MoodyCashFlowRating] varchar(1000),
[MoodyCashFlowRatingAdjusted] varchar(1000),
[MoodyFacilityRating] varchar(1000),
[MoodyRecovery] numeric (32,4),
[SnPIssuerRating] varchar(1000),
[SnPIssuerRatingAdjusted] varchar(1000),
[SnPFacilityRating] varchar(1000),
[SnPfacilityRatingAdjusted] varchar(1000),
[SnPRecoveryRating] varchar(1000),
[MoodyOutlook] varchar(1),
[MoodyWatch] varchar(1000),
[SnPWatch] varchar(1),
[NextReportingDate] varchar(20),
[FiscalYearEndDate] varchar(20),
[YieldBid]  numeric (32,2),
[YieldOffer] numeric (32,2),
[YieldMid] numeric (32,2),
[CappedYieldBid] numeric (32,2),
[CappedYieldOffer] numeric (32,2),
[CappedYieldMid] numeric (32,2),
[TargetYieldBid] numeric (32,2),
[TargetYieldOffer] numeric (32,2),
[TargetYieldMid] numeric (32,2),
[BetterWorseBid] numeric (32,2),
[BetterWorseOffer] numeric (32,2),
[BetterWorseMid] numeric (32,2),
[TotalCoupon] numeric (32,2),
[WARF] numeric (32,2),
[WARFRecovery] numeric (32,2),
[Life] numeric (32,2),
[TotalPar] varchar(1000),
[TotalParNum]  numeric (32,4),
[BODTotalPar]  numeric (32,4),
[MoodyFacilityRatingAdjusted] varchar(1000),
[CLOAnalyst]  varchar(1000),
[HFAnalyst]  varchar(1000),
[AsOfDate] varchar(10),
[CreditScore]  numeric (32,4),
[LiquidityScore]  numeric (32,4),
[OneLLeverage]  numeric (32,4),
[TotalLeverage]  varchar(1000),
[EVMultiple]  varchar(1000),
[LTMRevenues]  varchar(1000),
[LTMEBITDA]  varchar(1000),
[FCF]  varchar(1000),
[Comments]  varchar(1000),
[BusinessDescription]   varchar(1000),
[AgentBank]   varchar(1000),
[SecurityMaturityDate]   datetime,
[IsOnAlert] bit,
[LTMFCF] numeric(38,2),
[EnterpriseValue]  numeric(38,2),
[SeniorLeverage]  numeric(38,2),
[CostPrice] varchar(1000),
[CostPriceNum] numeric(28,10),
[PrevDayBidNum] numeric(28,10),
[PrevDayOfferNum] numeric(28,10),
[PrevDayBid] varchar(1000),
[PrevDayOffer] varchar(1000),
[PriceMove] numeric(28,10),
[SearchText]  varchar(1000),
[LienTypeId] smallint,
[ScoreDescription]  varchar(1000),
[GlobalAmount]  numeric(38,4),
[IsPrivate] bit,
[Sponsor] varchar(1000),
[CLO1MatrixImpliedSpread]  numeric(38,4),
[CLO2MatrixImpliedSpread]  numeric(38,4),
[CLO3MatrixImpliedSpread]  numeric(38,4),
[CLO4MatrixImpliedSpread]  numeric(38,4),
[CLO5MatrixImpliedSpread]  numeric(38,4),
[CLO6MatrixImpliedSpread]  numeric(38,4),
[CLO7MatrixImpliedSpread]  numeric(38,4),
[CLO1DifferentialImpliedSpread]   numeric(38,4),
[CLO2DifferentialImpliedSpread]   numeric(38,4),
[CLO3DifferentialImpliedSpread]   numeric(38,4),
[CLO4DifferentialImpliedSpread]   numeric(38,4),
[CLO5DifferentialImpliedSpread]   numeric(38,4),
[CLO6DifferentialImpliedSpread]   numeric(38,4),
[CLO7DifferentialImpliedSpread]   numeric(38,4), 
[CLO1MatrixWarfRecovery]  numeric(38,4),
[CLO2MatrixWarfRecovery]  numeric(38,4),
[CLO3MatrixWarfRecovery]  numeric(38,4),
[CLO4MatrixWarfRecovery]  numeric(38,4),
[CLO5MatrixWarfRecovery]  numeric(38,4),
[CLO6MatrixWarfRecovery]  numeric(38,4),
[CLO7MatrixWarfRecovery]  numeric(38,4),
CONSTRAINT [PK_AggregatedPositions] PRIMARY KEY ([Id]),
CONSTRAINT [UQ_AggregatedPositions_PositionDateId,SecurityId] UNIQUE(PositionDateId,SecurityId),
zSnPAssetRecoveryRating VARCHAR(2),
[SnpWarf]				NUMERIC (32,8),
[SnpLgd]				NUMERIC (32,8),
[MoodysLgd]				NUMERIC (32,8),
[YieldAvgLgd]			NUMERIC (32,8),
[SnpAAARecovery]		NUMERIC (32,8),
SnpCreditWatch			VARCHAR(5),
[LiborBaseRate]			VARCHAR(50),
[Fund-4 WARF]			NUMERIC (32,8) NULL,
[CLO8NumExposure] [NUMERIC](32, 4) NULL,
[CLO8Exposure] [VARCHAR](50) NULL,
[CLO8PctExposure] [VARCHAR](50) NULL,
[CLO8TargetPar] [NUMERIC](32, 4) NULL,
[CLO8MatrixImpliedSpread] [NUMERIC](38, 4) NULL,
[CLO8DifferentialImpliedSpread] [NUMERIC](38, 4) NULL,
[CLO8MatrixWarfRecovery] [NUMERIC](38, 4) NULL,
[Fund-5 WARF]			NUMERIC (32,8) NULL,
[LiborCategory] [VARCHAR](50) NULL,
[LiborTransitionNote] [VARCHAR](1000) NULL,
[Fund-4 MoodyRecovery] numeric (32,4),
[Fund-5 MoodyRecovery] numeric (32,4),
[IsInDefault] BIT NULL,
[DefaultDate] DATETIME NULL	,
[Fund-10 WARF]			NUMERIC (32,8) NULL,
[Fund-10 MoodyRecovery] numeric (32,4),
[Fund-2 WARF]			NUMERIC (32,8) NULL,
[Fund-2 MoodyRecovery] numeric (32,4),

[CLO9NumExposure] [NUMERIC](32, 4) NULL,
[CLO9Exposure] [VARCHAR](50) NULL,
[CLO9PctExposure] [VARCHAR](50) NULL,
[CLO9TargetPar] [NUMERIC](32, 4) NULL,
[CLO9MatrixImpliedSpread] [NUMERIC](38, 4) NULL,
[CLO9DifferentialImpliedSpread] [NUMERIC](38, 4) NULL,
[CLO9MatrixWarfRecovery] [NUMERIC](38, 4) NULL,

[Fund-1 WARF]			NUMERIC (32,8) NULL,
[Fund-1 MoodyRecovery] numeric (32,4),
[Fund-3 WARF]			NUMERIC (32,8) NULL,
[Fund-3 MoodyRecovery] numeric (32,4),


[Fund-7 WARF]			NUMERIC (32,8) NULL,
[Fund-7 MoodyRecovery] numeric (32,4),
[Fund-8 WARF]			NUMERIC (32,8) NULL,
[Fund-8 MoodyRecovery] numeric (32,4),
[Fund-9 WARF]			NUMERIC (32,8) NULL,
[Fund-9 MoodyRecovery] numeric (32,4)


)