CREATE TABLE [CLO].[OverrideMarketData]
(
	[OverrideMarketDataId] INT NOT NULL identity(1,1),
	[DateId] int not null ,
	[SecurityId]	int NOT NULL references		[CLO].[Security]([SecurityId]),
	[FundId] int not null references CLO.Fund(FundId),
	[Bid] numeric(38,10) ,
	[Offer] numeric(38,10), 
	[CostPrice] NUMERIC(38,10) null,
	[Spread] numeric(38,10) ,
	[LiborFloor] numeric(38,10) ,
	[MoodyCashFlowRatingId] SMALLINT NOT NULL references [CLO].[Rating]([RatingId]),
	[MoodyCashFlowRatingAdjustedId] SMALLINT NOT NULL references [CLO].[Rating]([RatingId]),
	[MoodyFacilityRatingId] SMALLINT references [CLO].[Rating]([RatingId]),
	[MoodyRecovery]	numeric(18,4) not null ,
	[SnPIssuerRatingId]		SMALLINT references [CLO].[Rating]([RatingId]),
	[SnPIssuerRatingAdjustedId] SMALLINT references [CLO].[Rating]([RatingId]),
	[SnPFacilityRatingId] SMALLINT references [CLO].[Rating]([RatingId]),
	[SnPfacilityRatingAdjustedId] SMALLINT references [CLO].[Rating]([RatingId]),
	[SnPRecoveryRatingId] SMALLINT references [CLO].[Rating]([RatingId]),
	[MoodyOutlook] varchar(1) ,
	[MoodyWatch] varchar(1) ,
	[SnPWatch] varchar(1) ,
	[NextReportingDate] datetime null,
	[FiscalYearEndDate] datetime null,
	[AgentBank] varchar(100) null, 
	[CreatedOn] datetime default (getdate()),
	[CreatedBy] varchar(100) null,
	[LastUpdatedOn] datetime default (getdate()),
	[LastUpdatedBy] varchar(100) null, 
	[SnpCreditWatch] VARCHAR(5),
	[LiborBaseRate] numeric(38,10) null,
	[MoodyDPRatingId] smallint references [CLO].[Rating]([RatingId]),
    PRIMARY KEY ([DateId],[FundId],[SecurityId]),
)
