/*
Deployment script for Yoda

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar YorkCore_Geneva "YorkCore_Geneva"
:setvar DatabaseName "Yoda"
:setvar DefaultFilePrefix "Yoda"
:setvar DefaultDataPath "E:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "F:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\Data\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET RECOVERY FULL 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET DISABLE_BROKER 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF IS_SRVROLEMEMBER(N'sysadmin') = 1
    BEGIN
        IF EXISTS (SELECT 1
                   FROM   [master].[dbo].[sysdatabases]
                   WHERE  [name] = N'$(DatabaseName)')
            BEGIN
                EXECUTE sp_executesql N'ALTER DATABASE [$(DatabaseName)]
    SET TRUSTWORTHY OFF 
    WITH ROLLBACK IMMEDIATE';
            END
    END
ELSE
    BEGIN
        PRINT N'The database settings cannot be modified. You must be a SysAdmin to apply these settings.';
    END


GO
PRINT N'Altering [CLO].[spGetFields]...';


GO
ALTER PROCEDURE [CLO].[spGetFields]
	@paramFieldGroupName VARCHAR(100)
AS
	if(@paramFieldGroupName = 'Matrix Point Based Fund Restrictions Fields')
	begin
		SELECT * FROM [CLO].[Field] f WITH(NOLOCK) 
		JOIN [CLO].[FieldGroup] fg ON f.FieldGroupId = fg.FieldGroupId 
		WHERE 
		f.FieldTitle in ('WARF', 'SPREAD', 'DIVERSITY')
		AND fg.FieldGroupName = 'Fund Restrictions'
		AND f.FieldName LIKE ('WSO%')
		ORDER BY f.SortOrder
	end
	else 
	begin
		SELECT * FROM [CLO].[Field] f WITH(NOLOCK) 
		JOIN [CLO].[FieldGroup] fg ON f.FieldGroupId = fg.FieldGroupId 
		WHERE 
	
		fg.FieldGroupName = @paramFieldGroupName
		ORDER BY f.SortOrder
	end
RETURN 0
GO
PRINT N'Update complete.';


GO


USE [Yoda]
GO

declare @parameterTypeId smallint

INSERT INTO [CLO].[ParameterType]
           ([ParameterTypeName])
     VALUES
           ('Matrix Point - Fund Restriction')

select @parameterTypeId = SCOPE_IDENTITY()

INSERT INTO [CLO].[ParameterValue]
           ([ParameterTypeId]
           ,[ParameterValueNumber]
           ,[ParameterValueText]
           ,[ParameterMinValueNumber]
           ,[ParameterMaxValueNumber])
     VALUES
           (6
           ,NULL
           ,'SPREAD'
           ,0.0005
           ,0.0005),
		   (6
           ,NULL
           ,'WARF'
           ,40
           ,40),
		   (6
           ,NULL
           ,'DIVERSITY'
           ,5
           ,5),(6
           ,NULL
           ,'WARF RECOVERY'
           ,43
           ,43)
GO

--Run this for 1,2,3,4,7
DECLARE 
@MatrixPoint INT
@WarfRecovery DECIMAL(28,10) = 43, @Spread  DECIMAL(28,10) = .0005, @Warf DECIMAL(28,10) = 40, @Diversity DECIMAL(28,10) = 5


DECLARE @matrixWarfRecovery DECIMAL(28,10), @matrixSpread  DECIMAL(28,10), 
@matrixWarf   DECIMAL(28,10), @matrixWarfModifier DECIMAL(28,10), @matrixDiversity DECIMAL(28,10)

DECLARE @fundMoodysRecovery DECIMAL(28,10)

SELECT TOP 1 @fundMoodysRecovery = MoodyRecovery FROM CLO.FundCalculation WHERE FundId = @FundId ORDER BY DateId DESC

SELECT *,
ROW_NUMBER() OVER(PARTITION BY FundId ORDER BY CreatedOn DESC) AS Rownum
INTO #matrixdatas
FROM clo.MatrixPoint WHERE FundId  = @FundId

 DELETE FROM #matrixdatas WHERE Rownum > 1

 SELECT TOP 1 
 @matrixSpread = Spread,
 @matrixWarfModifier = WARFModifier,
 @matrixWarf = WARF,
 @matrixDiversity = Diversity
 FROM #matrixdatas

 SELECT * FROM #matrixdatas
 
 SELECT @matrixWarf '@matrixWarf',@fundMoodysRecovery AS '@fundMoodysRecovery',@WarfRecovery  '@WarfRecovery', @matrixWarfModifier '@matrixWarfModifier'


 SELECT @matrixWarfRecovery = @matrixWarf + ((@fundMoodysRecovery - @WarfRecovery) * @matrixWarfModifier)

  SELECT @matrixWarfRecovery

 UPDATE fr
 SET fr.RestrictionValue = (@matrixSpread + @Spread)*100
 FROM clo.FundRestriction fr
 JOIN CLO.Field fi ON fi.FieldId = fr.FieldId
 WHERE  FundRestrictionTypeId = 1 AND FundId = @FundId AND fi.FieldTitle = 'SPREAD'

 UPDATE fr
 SET fr.RestrictionValue = @matrixSpread * 100 
 FROM clo.FundRestriction fr
 JOIN CLO.Field fi ON fi.FieldId = fr.FieldId
 WHERE  FundRestrictionTypeId = 2 AND FundId = @FundId AND fi.FieldTitle = 'SPREAD'

 SELECT @matrixWarfRecovery

 UPDATE fr
 SET fr.RestrictionValue = round(@matrixWarfRecovery - @Warf,0)
 FROM clo.FundRestriction fr
 JOIN CLO.Field fi ON fi.FieldId = fr.FieldId
 WHERE  FundRestrictionTypeId = 1 AND FundId = @FundId AND fi.FieldTitle = 'WARF'

 UPDATE fr
 SET fr.RestrictionValue = round(@matrixWarfRecovery ,0)
 FROM clo.FundRestriction fr
 JOIN CLO.Field fi ON fi.FieldId = fr.FieldId
 WHERE  FundRestrictionTypeId = 2 AND FundId = @FundId AND fi.FieldTitle = 'WARF'


 UPDATE fr
 SET fr.RestrictionValue = @matrixDiversity + @Diversity
 FROM clo.FundRestriction fr
 JOIN CLO.Field fi ON fi.FieldId = fr.FieldId
 WHERE  FundRestrictionTypeId = 1 AND FundId = @FundId AND fi.FieldTitle = 'DIVERSITY'

 UPDATE fr
 SET fr.RestrictionValue = @matrixDiversity 
 FROM clo.FundRestriction fr
 JOIN CLO.Field fi ON fi.FieldId = fr.FieldId
 WHERE  FundRestrictionTypeId = 2 AND FundId = @FundId AND fi.FieldTitle = 'DIVERSITY'


 DROP TABLE #matrixdatas


 Go
 DECLARE 
@MatrixPoint INT, @FundId INT = 2,
@WarfRecovery DECIMAL(28,10) = 43, @Spread  DECIMAL(28,10) = .0005, @Warf DECIMAL(28,10) = 40, @Diversity DECIMAL(28,10) = 5


DECLARE @matrixWarfRecovery DECIMAL(28,10), @matrixSpread  DECIMAL(28,10), 
@matrixWarf   DECIMAL(28,10), @matrixWarfModifier DECIMAL(28,10), @matrixDiversity DECIMAL(28,10)

DECLARE @fundMoodysRecovery DECIMAL(28,10)

SELECT TOP 1 @fundMoodysRecovery = MoodyRecovery FROM CLO.FundCalculation WHERE FundId = @FundId ORDER BY DateId DESC

SELECT *,
ROW_NUMBER() OVER(PARTITION BY FundId ORDER BY CreatedOn DESC) AS Rownum
INTO #matrixdatas
FROM clo.MatrixPoint WHERE FundId  = @FundId

 DELETE FROM #matrixdatas WHERE Rownum > 1

 SELECT TOP 1 
 @matrixSpread = Spread,
 @matrixWarfModifier = WARFModifier,
 @matrixWarf = WARF,
 @matrixDiversity = Diversity
 FROM #matrixdatas

 SELECT * FROM #matrixdatas
 
 SELECT @matrixWarf '@matrixWarf',@fundMoodysRecovery AS '@fundMoodysRecovery',@WarfRecovery  '@WarfRecovery', @matrixWarfModifier '@matrixWarfModifier'


 SELECT @matrixWarfRecovery = @matrixWarf + ((@fundMoodysRecovery - @WarfRecovery) * @matrixWarfModifier)

  SELECT @matrixWarfRecovery

 UPDATE fr
 SET fr.RestrictionValue = (@matrixSpread + @Spread)*100
 FROM clo.FundRestriction fr
 JOIN CLO.Field fi ON fi.FieldId = fr.FieldId
 WHERE  FundRestrictionTypeId = 1 AND FundId = @FundId AND fi.FieldTitle = 'SPREAD'

 UPDATE fr
 SET fr.RestrictionValue = @matrixSpread * 100 
 FROM clo.FundRestriction fr
 JOIN CLO.Field fi ON fi.FieldId = fr.FieldId
 WHERE  FundRestrictionTypeId = 2 AND FundId = @FundId AND fi.FieldTitle = 'SPREAD'

 SELECT @matrixWarfRecovery

 UPDATE fr
 SET fr.RestrictionValue = round(@matrixWarfRecovery - @Warf,0)
 FROM clo.FundRestriction fr
 JOIN CLO.Field fi ON fi.FieldId = fr.FieldId
 WHERE  FundRestrictionTypeId = 1 AND FundId = @FundId AND fi.FieldTitle = 'WARF'

 UPDATE fr
 SET fr.RestrictionValue = round(@matrixWarfRecovery ,0)
 FROM clo.FundRestriction fr
 JOIN CLO.Field fi ON fi.FieldId = fr.FieldId
 WHERE  FundRestrictionTypeId = 2 AND FundId = @FundId AND fi.FieldTitle = 'WARF'


 UPDATE fr
 SET fr.RestrictionValue = @matrixDiversity + @Diversity
 FROM clo.FundRestriction fr
 JOIN CLO.Field fi ON fi.FieldId = fr.FieldId
 WHERE  FundRestrictionTypeId = 1 AND FundId = @FundId AND fi.FieldTitle = 'DIVERSITY'

 UPDATE fr
 SET fr.RestrictionValue = @matrixDiversity 
 FROM clo.FundRestriction fr
 JOIN CLO.Field fi ON fi.FieldId = fr.FieldId
 WHERE  FundRestrictionTypeId = 2 AND FundId = @FundId AND fi.FieldTitle = 'DIVERSITY'


 DROP TABLE #matrixdatas

 
 Go
 DECLARE 
@MatrixPoint INT, @FundId INT = 3,
@WarfRecovery DECIMAL(28,10) = 43, @Spread  DECIMAL(28,10) = .0005, @Warf DECIMAL(28,10) = 40, @Diversity DECIMAL(28,10) = 5


DECLARE @matrixWarfRecovery DECIMAL(28,10), @matrixSpread  DECIMAL(28,10), 
@matrixWarf   DECIMAL(28,10), @matrixWarfModifier DECIMAL(28,10), @matrixDiversity DECIMAL(28,10)

DECLARE @fundMoodysRecovery DECIMAL(28,10)

SELECT TOP 1 @fundMoodysRecovery = MoodyRecovery FROM CLO.FundCalculation WHERE FundId = @FundId ORDER BY DateId DESC

SELECT *,
ROW_NUMBER() OVER(PARTITION BY FundId ORDER BY CreatedOn DESC) AS Rownum
INTO #matrixdatas
FROM clo.MatrixPoint WHERE FundId  = @FundId

 DELETE FROM #matrixdatas WHERE Rownum > 1

 SELECT TOP 1 
 @matrixSpread = Spread,
 @matrixWarfModifier = WARFModifier,
 @matrixWarf = WARF,
 @matrixDiversity = Diversity
 FROM #matrixdatas

 SELECT * FROM #matrixdatas
 
 SELECT @matrixWarf '@matrixWarf',@fundMoodysRecovery AS '@fundMoodysRecovery',@WarfRecovery  '@WarfRecovery', @matrixWarfModifier '@matrixWarfModifier'


 SELECT @matrixWarfRecovery = @matrixWarf + ((@fundMoodysRecovery - @WarfRecovery) * @matrixWarfModifier)

  SELECT @matrixWarfRecovery

 UPDATE fr
 SET fr.RestrictionValue = (@matrixSpread + @Spread)*100
 FROM clo.FundRestriction fr
 JOIN CLO.Field fi ON fi.FieldId = fr.FieldId
 WHERE  FundRestrictionTypeId = 1 AND FundId = @FundId AND fi.FieldTitle = 'SPREAD'

 UPDATE fr
 SET fr.RestrictionValue = @matrixSpread * 100 
 FROM clo.FundRestriction fr
 JOIN CLO.Field fi ON fi.FieldId = fr.FieldId
 WHERE  FundRestrictionTypeId = 2 AND FundId = @FundId AND fi.FieldTitle = 'SPREAD'

 SELECT @matrixWarfRecovery

 UPDATE fr
 SET fr.RestrictionValue = round(@matrixWarfRecovery - @Warf,0)
 FROM clo.FundRestriction fr
 JOIN CLO.Field fi ON fi.FieldId = fr.FieldId
 WHERE  FundRestrictionTypeId = 1 AND FundId = @FundId AND fi.FieldTitle = 'WARF'

 UPDATE fr
 SET fr.RestrictionValue = round(@matrixWarfRecovery ,0)
 FROM clo.FundRestriction fr
 JOIN CLO.Field fi ON fi.FieldId = fr.FieldId
 WHERE  FundRestrictionTypeId = 2 AND FundId = @FundId AND fi.FieldTitle = 'WARF'


 UPDATE fr
 SET fr.RestrictionValue = @matrixDiversity + @Diversity
 FROM clo.FundRestriction fr
 JOIN CLO.Field fi ON fi.FieldId = fr.FieldId
 WHERE  FundRestrictionTypeId = 1 AND FundId = @FundId AND fi.FieldTitle = 'DIVERSITY'

 UPDATE fr
 SET fr.RestrictionValue = @matrixDiversity 
 FROM clo.FundRestriction fr
 JOIN CLO.Field fi ON fi.FieldId = fr.FieldId
 WHERE  FundRestrictionTypeId = 2 AND FundId = @FundId AND fi.FieldTitle = 'DIVERSITY'


 DROP TABLE #matrixdatas


 
 Go
 DECLARE 
@MatrixPoint INT, @FundId INT = 4,
@WarfRecovery DECIMAL(28,10) = 43, @Spread  DECIMAL(28,10) = .0005, @Warf DECIMAL(28,10) = 40, @Diversity DECIMAL(28,10) = 5


DECLARE @matrixWarfRecovery DECIMAL(28,10), @matrixSpread  DECIMAL(28,10), 
@matrixWarf   DECIMAL(28,10), @matrixWarfModifier DECIMAL(28,10), @matrixDiversity DECIMAL(28,10)

DECLARE @fundMoodysRecovery DECIMAL(28,10)

SELECT TOP 1 @fundMoodysRecovery = MoodyRecovery FROM CLO.FundCalculation WHERE FundId = @FundId ORDER BY DateId DESC

SELECT *,
ROW_NUMBER() OVER(PARTITION BY FundId ORDER BY CreatedOn DESC) AS Rownum
INTO #matrixdatas
FROM clo.MatrixPoint WHERE FundId  = @FundId

 DELETE FROM #matrixdatas WHERE Rownum > 1

 SELECT TOP 1 
 @matrixSpread = Spread,
 @matrixWarfModifier = WARFModifier,
 @matrixWarf = WARF,
 @matrixDiversity = Diversity
 FROM #matrixdatas

 SELECT * FROM #matrixdatas
 
 SELECT @matrixWarf '@matrixWarf',@fundMoodysRecovery AS '@fundMoodysRecovery',@WarfRecovery  '@WarfRecovery', @matrixWarfModifier '@matrixWarfModifier'


 SELECT @matrixWarfRecovery = @matrixWarf + ((@fundMoodysRecovery - @WarfRecovery) * @matrixWarfModifier)

  SELECT @matrixWarfRecovery

 UPDATE fr
 SET fr.RestrictionValue = (@matrixSpread + @Spread)*100
 FROM clo.FundRestriction fr
 JOIN CLO.Field fi ON fi.FieldId = fr.FieldId
 WHERE  FundRestrictionTypeId = 1 AND FundId = @FundId AND fi.FieldTitle = 'SPREAD'

 UPDATE fr
 SET fr.RestrictionValue = @matrixSpread * 100 
 FROM clo.FundRestriction fr
 JOIN CLO.Field fi ON fi.FieldId = fr.FieldId
 WHERE  FundRestrictionTypeId = 2 AND FundId = @FundId AND fi.FieldTitle = 'SPREAD'

 SELECT @matrixWarfRecovery

 UPDATE fr
 SET fr.RestrictionValue = round(@matrixWarfRecovery - @Warf,0)
 FROM clo.FundRestriction fr
 JOIN CLO.Field fi ON fi.FieldId = fr.FieldId
 WHERE  FundRestrictionTypeId = 1 AND FundId = @FundId AND fi.FieldTitle = 'WARF'

 UPDATE fr
 SET fr.RestrictionValue = round(@matrixWarfRecovery ,0)
 FROM clo.FundRestriction fr
 JOIN CLO.Field fi ON fi.FieldId = fr.FieldId
 WHERE  FundRestrictionTypeId = 2 AND FundId = @FundId AND fi.FieldTitle = 'WARF'


 UPDATE fr
 SET fr.RestrictionValue = @matrixDiversity + @Diversity
 FROM clo.FundRestriction fr
 JOIN CLO.Field fi ON fi.FieldId = fr.FieldId
 WHERE  FundRestrictionTypeId = 1 AND FundId = @FundId AND fi.FieldTitle = 'DIVERSITY'

 UPDATE fr
 SET fr.RestrictionValue = @matrixDiversity 
 FROM clo.FundRestriction fr
 JOIN CLO.Field fi ON fi.FieldId = fr.FieldId
 WHERE  FundRestrictionTypeId = 2 AND FundId = @FundId AND fi.FieldTitle = 'DIVERSITY'


 DROP TABLE #matrixdatas

 GO

 
 Go
 DECLARE 
@MatrixPoint INT, @FundId INT = 7,
@WarfRecovery DECIMAL(28,10) = 43, @Spread  DECIMAL(28,10) = .0005, @Warf DECIMAL(28,10) = 40, @Diversity DECIMAL(28,10) = 5


DECLARE @matrixWarfRecovery DECIMAL(28,10), @matrixSpread  DECIMAL(28,10), 
@matrixWarf   DECIMAL(28,10), @matrixWarfModifier DECIMAL(28,10), @matrixDiversity DECIMAL(28,10)

DECLARE @fundMoodysRecovery DECIMAL(28,10)

SELECT TOP 1 @fundMoodysRecovery = MoodyRecovery FROM CLO.FundCalculation WHERE FundId = @FundId ORDER BY DateId DESC

SELECT *,
ROW_NUMBER() OVER(PARTITION BY FundId ORDER BY CreatedOn DESC) AS Rownum
INTO #matrixdatas
FROM clo.MatrixPoint WHERE FundId  = @FundId

 DELETE FROM #matrixdatas WHERE Rownum > 1

 SELECT TOP 1 
 @matrixSpread = Spread,
 @matrixWarfModifier = WARFModifier,
 @matrixWarf = WARF,
 @matrixDiversity = Diversity
 FROM #matrixdatas

 SELECT * FROM #matrixdatas
 
 SELECT @matrixWarf '@matrixWarf',@fundMoodysRecovery AS '@fundMoodysRecovery',@WarfRecovery  '@WarfRecovery', @matrixWarfModifier '@matrixWarfModifier'


 SELECT @matrixWarfRecovery = @matrixWarf + ((@fundMoodysRecovery - @WarfRecovery) * @matrixWarfModifier)

  SELECT @matrixWarfRecovery

 UPDATE fr
 SET fr.RestrictionValue = (@matrixSpread + @Spread)*100
 FROM clo.FundRestriction fr
 JOIN CLO.Field fi ON fi.FieldId = fr.FieldId
 WHERE  FundRestrictionTypeId = 1 AND FundId = @FundId AND fi.FieldTitle = 'SPREAD'

 UPDATE fr
 SET fr.RestrictionValue = @matrixSpread * 100 
 FROM clo.FundRestriction fr
 JOIN CLO.Field fi ON fi.FieldId = fr.FieldId
 WHERE  FundRestrictionTypeId = 2 AND FundId = @FundId AND fi.FieldTitle = 'SPREAD'

 SELECT @matrixWarfRecovery

 UPDATE fr
 SET fr.RestrictionValue = round(@matrixWarfRecovery - @Warf,0)
 FROM clo.FundRestriction fr
 JOIN CLO.Field fi ON fi.FieldId = fr.FieldId
 WHERE  FundRestrictionTypeId = 1 AND FundId = @FundId AND fi.FieldTitle = 'WARF'

 UPDATE fr
 SET fr.RestrictionValue = round(@matrixWarfRecovery ,0)
 FROM clo.FundRestriction fr
 JOIN CLO.Field fi ON fi.FieldId = fr.FieldId
 WHERE  FundRestrictionTypeId = 2 AND FundId = @FundId AND fi.FieldTitle = 'WARF'


 UPDATE fr
 SET fr.RestrictionValue = @matrixDiversity + @Diversity
 FROM clo.FundRestriction fr
 JOIN CLO.Field fi ON fi.FieldId = fr.FieldId
 WHERE  FundRestrictionTypeId = 1 AND FundId = @FundId AND fi.FieldTitle = 'DIVERSITY'

 UPDATE fr
 SET fr.RestrictionValue = @matrixDiversity 
 FROM clo.FundRestriction fr
 JOIN CLO.Field fi ON fi.FieldId = fr.FieldId
 WHERE  FundRestrictionTypeId = 2 AND FundId = @FundId AND fi.FieldTitle = 'DIVERSITY'


 DROP TABLE #matrixdatas