/*
Deployment script for Yoda

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar YorkCore_Geneva "YorkCore_Geneva"
:setvar DatabaseName "Yoda"
:setvar DefaultFilePrefix "Yoda"
:setvar DefaultDataPath "E:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "F:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\Data\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET RECOVERY FULL 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET DISABLE_BROKER 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF IS_SRVROLEMEMBER(N'sysadmin') = 1
    BEGIN
        IF EXISTS (SELECT 1
                   FROM   [master].[dbo].[sysdatabases]
                   WHERE  [name] = N'$(DatabaseName)')
            BEGIN
                EXECUTE sp_executesql N'ALTER DATABASE [$(DatabaseName)]
    SET TRUSTWORTHY OFF 
    WITH ROLLBACK IMMEDIATE';
            END
    END
ELSE
    BEGIN
        PRINT N'The database settings cannot be modified. You must be a SysAdmin to apply these settings.';
    END


GO
PRINT N'Removing schema binding from [CLO].[vw_Calculation]...';


GO
ALTER VIEW [CLO].[vw_Calculation]
AS
SELECT CalculationId,
       DateId,
       SecurityId,
       FundId,
       YieldBid,
       YieldOffer,
       YieldMid,
       CappedYieldBid,
       CappedYieldOffer,
       CappedYieldMid,
       TargetYieldBid,
       TargetYieldOffer,
       TargetYieldMid,
       BetterWorseBid,
       BetterWorseOffer,
       BetterWorseMid,
       TotalCoupon,
       WARF,
       WARFRecovery,
       Life,
       TotalPar,
       moodyfacilityratingadjusted.RatingDesc AS MoodyFacilityRatingAdjusted,
       c.CreatedOn,
       c.CreatedBy,
       c.LastUpdatedOn,
       c.LastUpdatedBy,
       c.MatrixImpliedSpread,
       c.MatrixWARFRecovery,
       ROW_NUMBER() OVER (PARTITION BY SecurityId, FundId ORDER BY DateId DESC) AS RowNumber
FROM   CLO.Calculation AS c WITH (NOLOCK)
       LEFT OUTER JOIN
       CLO.Rating AS moodyfacilityratingadjusted WITH (NOLOCK)
       ON moodyfacilityratingadjusted.RatingId = c.MoodyFacilityRatingAdjustedId
WHERE  DateId = CLO.GetPrevDayDateId();


GO
PRINT N'Altering [CLO].[Calculation]...';


GO
ALTER TABLE [CLO].[Calculation]
    ADD [zSnPAssetRecoveryRating] VARCHAR (2) NULL;


GO
PRINT N'Altering [CLO].[WSOPosition]...';


GO
ALTER TABLE [CLO].[WSOPosition]
    ADD [SnPAssetRecoveryRating] VARCHAR (100) NULL;


GO
PRINT N'Adding schema binding to [CLO].[vw_Calculation]...';


GO
ALTER VIEW CLO.vw_Calculation WITH SCHEMABINDING 
	AS 
	SELECT 
	  CalculationId
	, DateId
	, SecurityId
	, FundId
	, YieldBid
	, YieldOffer
	, YieldMid
	, CappedYieldBid
	, CappedYieldOffer
	, CappedYieldMid
	, TargetYieldBid
	, TargetYieldOffer
	, TargetYieldMid
	, BetterWorseBid
	, BetterWorseOffer
	, BetterWorseMid
	, TotalCoupon
	, WARF
	, WARFRecovery
	, Life
	, TotalPar
	, moodyfacilityratingadjusted.RatingDesc as MoodyFacilityRatingAdjusted
	, c.CreatedOn
	, c.CreatedBy
	, c.LastUpdatedOn
	, c.LastUpdatedBy
	, c.MatrixImpliedSpread
	, c.MatrixWARFRecovery
	, c.zSnPAssetRecoveryRating
	, ROW_NUMBER() OVER (PARTITION BY SecurityId, FundId
			ORDER BY DateId DESC) AS RowNumber
	FROM CLO.Calculation c (NOLOCK)
	LEFT JOIN CLO.Rating moodyfacilityratingadjusted (NOLOCK) ON moodyfacilityratingadjusted.RatingId = c.MoodyFacilityRatingAdjustedId
	WHERE DateId = CLO.GetPrevDayDateId()
GO
PRINT N'Altering [CLO].[spCleanPositionsBasedOnPrincipalCash]...';


GO
ALTER PROCEDURE [CLO].[spCleanPositionsBasedOnPrincipalCash]
	@fundId int = 0,
	@dateId INT
AS
	declare @positionsCount int = 0

	select @positionsCount = count(*) 
	from  [CLO].Position p with(nolock)
	where p.DateId = @dateId and p.FundId = @fundId 


	if (@positionsCount <> 0)
	BEGIN
		
		DELETE FROM [CLO].[WSOPosition]   WHERE DateId = @dateId and FundId = @fundId
		DELETE FROM [CLO].[WSOMarketData] WHERE DateId = @dateId and FundId = @fundId

		INSERT INTO [CLO].[WSOPosition]  ([FundId]
           ,[SecurityId]
           ,[DateId]
           ,[MarketValue]
           ,[Exposure]
           ,[PctExposure]
           ,[PxPrice]
           ,[IsCovLite]
           ,[CountryId]
           ,[CreatedOn]
           ,[CreatedBy]
           ,[LastUpdatedOn]
           ,[LastUpdatedBy]
           ,[IsStale]
		   ,[CapitalizedInterestOrig]
		   ,[SnPAssetRecoveryRating]
		   )
		   SELECT 
		   [FundId]
           ,[SecurityId]
           ,[DateId]
           ,[MarketValue]
           ,[Exposure]
           ,[PctExposure]
           ,[PxPrice]
           ,[IsCovLite]
           ,[CountryId]
           ,[CreatedOn]
           ,[CreatedBy]
           ,[LastUpdatedOn]
           ,[LastUpdatedBy]
           ,[IsStale]
		   ,[CapitalizedInterestOrig]
		   ,[SnPAssetRecoveryRating]
		   FROM [CLO].Position WHERE DateID = @dateId AND ISNULL(IsStale,0) = 0  and FundId = @fundId
		
		INSERT INTO [CLO].[WSOMarketData]
           ([DateId]
           ,[SecurityId]
           ,[FundId]
           ,[Bid]
           ,[Offer]
           ,[CostPrice]
           ,[Spread]
           ,[LiborFloor]
           ,[MoodyCashFlowRatingId]
           ,[MoodyCashFlowRatingAdjustedId]
           ,[MoodyFacilityRatingId]
           ,[MoodyRecovery]
           ,[SnPIssuerRatingId]
           ,[SnPIssuerRatingAdjustedId]
           ,[SnPFacilityRatingId]
           ,[SnPfacilityRatingAdjustedId]
           ,[SnPRecoveryRatingId]
           ,[MoodyOutlook]
           ,[MoodyWatch]
           ,[SnPWatch]
           ,[NextReportingDate]
           ,[FiscalYearEndDate]
           ,[AgentBank]
           ,[CreatedOn]
           ,[CreatedBy]
           ,[LastUpdatedOn]
           ,[LastUpdatedBy]
		   ,[IsStale]
		   )
		   SELECT 
		   [DateId]
           ,[SecurityId]
           ,[FundId]
           ,[Bid]
           ,[Offer]
           ,[CostPrice]
           ,[Spread]
           ,[LiborFloor]
           ,[MoodyCashFlowRatingId]
           ,[MoodyCashFlowRatingAdjustedId]
           ,[MoodyFacilityRatingId]
           ,[MoodyRecovery]
           ,[SnPIssuerRatingId]
           ,[SnPIssuerRatingAdjustedId]
           ,[SnPFacilityRatingId]
           ,[SnPfacilityRatingAdjustedId]
           ,[SnPRecoveryRatingId]
           ,[MoodyOutlook]
           ,[MoodyWatch]
           ,[SnPWatch]
           ,[NextReportingDate]
           ,[FiscalYearEndDate]
           ,[AgentBank]
           ,[CreatedOn]
           ,[CreatedBy]
           ,[LastUpdatedOn]
           ,[LastUpdatedBy]
		   ,[IsStale]
		FROM [CLO].MarketData WHERE DateID = @dateId AND ISNULL(IsStale,0) = 0  and FundId = @fundId

		DELETE FROM CLO.Position	WHERE DateId = @dateId  and FundId = @fundId
		DELETE FROM CLO.MarketData	WHERE DateId = @dateId  and FundId = @fundId
		
	END


RETURN 0
GO
PRINT N'Refreshing [CLO].[spGenerateAggregatedPositions]...';


GO
EXECUTE sp_refreshsqlmodule N'[CLO].[spGenerateAggregatedPositions]';


GO
PRINT N'Refreshing [CLO].[LoadWso_Position]...';


GO
EXECUTE sp_refreshsqlmodule N'[CLO].[LoadWso_Position]';


GO
PRINT N'Refreshing [CLO].[spRefillPositionsBasedOnPrincipalCash]...';


GO
EXECUTE sp_refreshsqlmodule N'[CLO].[spRefillPositionsBasedOnPrincipalCash]';


GO
PRINT N'Refreshing [CLO].[LoadWso_ByDatasetKeys]...';


GO
EXECUTE sp_refreshsqlmodule N'[CLO].[LoadWso_ByDatasetKeys]';


GO
PRINT N'Refreshing [CLO].[LoadWso]...';


GO
EXECUTE sp_refreshsqlmodule N'[CLO].[LoadWso]';


GO
PRINT N'Update complete.';


GO
alter VIEW CLO.vw_Position
AS
WITH prev_position
AS	(
		SELECT PositionId, FundId, SecurityId, DateId, MarketValue, Exposure, PctExposure, PxPrice, IsCovLite, CountryId
			, CreatedOn, CreatedBy, LastUpdatedOn, LastUpdatedBy, IsStale, CapitalizedInterestOrig,[SnPAssetRecoveryRating]
		FROM CLO.Position WITH (NOLOCK)
		WHERE DateId = CLO.GetPrevDayDateId() OR PositionId IS NULL
	)
SELECT p.PositionId, p.DateId PositionDateId
	, FORMAT(NULLIF((ISNULL(p.Exposure, 0) + ISNULL(s.Allocation, 0)), 0), '#,###') Exposure
	, (ISNULL(p.Exposure, 0) + ISNULL(s.Allocation, 0)) NumExposure, ISNULL(p.Exposure, 0) BODExposure
	, ISNULL(p.Exposure, 0) + ISNULL((CASE WHEN s.HasBuy = 1 THEN s.Allocation ELSE 0 END), 0) BODwithBuyExposure
	, FORMAT(((ISNULL(p.Exposure, 0) + ISNULL(s.Allocation, 0)) / s.TargetPar), 'p') PctExposure
	, ISNULL(p.CapitalizedInterestOrig, 0) CapitalizedInterestOrig,
	p.[SnPAssetRecoveryRating],
	p.PxPrice
	, ((ISNULL(p.Exposure, 0) + ISNULL(s.Allocation, 0)) / s.TargetPar) PctExposureNum, s.FundId, s.FundCode
	, s.FundDesc, s.SecurityId, s.SecurityCode, s.SecurityDesc, s.BBGId, s.Issuer, s.IssuerId
	, s.IssuerDesc, LTRIM(s.Facility) Facility
	, CASE WHEN s.CallDate <> '1900-01-01' THEN CONVERT(VARCHAR(10), s.CallDate, 101) ELSE NULL END CallDate
	, country.CountryDesc, CONVERT(VARCHAR(10), s.MaturityDate, 101) MaturityDate
	, s.SnpIndustry, s.MoodyIndustry, CASE WHEN (p.IsCovLite = 1) THEN 'Y' ELSE 'N' END IsCovLite
	, CASE WHEN (s.IsFloating = 1) THEN 'Floating' ELSE 'Fixed' END IsFloating
	, s.LienType

	, s.IsOnWatch, s.WatchObjectTypeId, s.WatchObjectId, s.WatchId, s.WatchComments, s.WatchLastUpdatedOn, s.WatchUser

	, s.SellCandidateObjectTypeId, s.SellCandidateObjectId, s.SellCandidateId, s.SellCandidateComments , s.SellCandidateLastUpdatedOn, s.SellCandidateUser

	, s.OrigSecurityCode, s.OrigSecurityDesc, s.OrigBBGId
	, s.OrigIssuer, s.OrigFacility, s.OrigCallDate, s.OrigMaturityDate, s.OrigSnpIndustry
	, s.OrigMoodyIndustry, s.OrigIsFloating, s.OrigLienType
	, c.MoodyFacilityRatingAdjusted AS OrigMoodyFacilityRatingAdjusted
	, m.MoodyCashFlowRatingAdjusted AS OrigMoodyCashFlowRatingAdjusted, s.PrincipalCash, s.LiabilityPar, s.EquityPar
	, s.MoodyIndustryId, s.SecurityLastUpdatedOn, s.SecurityLastUpdatedBy, s.SecurityCreatedOn
	, s.SecurityCreatedBy, m.DateId MarketDateId, m.MarketDataId, m.OverrideMarketDataId
	, CONVERT(VARCHAR, CAST(m.Bid AS MONEY), 1) Bid, CONVERT(VARCHAR, CAST(m.Offer AS MONEY), 1) Offer
	, CONVERT(VARCHAR, CAST(pm.Bid AS MONEY), 1) PrevDayBid
	, CONVERT(VARCHAR, CAST(pm.Offer AS MONEY), 1) PrevDayOffer
	, CONVERT(VARCHAR, CAST(m.CostPrice AS MONEY), 1) CostPrice, m.CostPrice CostPriceNum, m.Bid BidNum
	, m.Offer OfferNum
	, CASE WHEN ISNULL(m.Bid, 0) <> 0 AND ISNULL(pm.Bid, 0) <> 0 THEN FORMAT(((m.Bid - pm.Bid) / m.Bid), 'p') ELSE NULL END PctBidDiff
	, CASE WHEN ISNULL(m.Bid, 0) <> 0 AND ISNULL(pm.Bid, 0) <> 0 THEN ((m.Bid - pm.Bid) / m.Bid) ELSE NULL END PctBidDiffNum
	, CASE WHEN ISNULL(m.Offer, 0) <> 0 AND ISNULL(pm.Offer, 0) <> 0 THEN FORMAT(((m.Offer - pm.Offer) / m.Offer), 'p') ELSE NULL END PctOfferDiff
	, CASE WHEN ISNULL(m.Offer, 0) <> 0 AND ISNULL(pm.Offer, 0) <> 0 THEN ((m.Offer - pm.Offer) / m.Offer) ELSE NULL END PctOfferDiffNum
	, CASE WHEN ISNULL(m.Bid, 0) <> 0 AND ISNULL(pm.Bid, 0) <> 0 THEN (m.Bid - pm.Bid) ELSE NULL END PriceMove
	, pm.Bid PrevDayBidNum, pm.Offer PrevDayOfferNum
	, CAST(m.Spread AS NUMERIC(20, 2)) Spread, CAST(m.LiborFloor AS NUMERIC(20, 2)) LiborFloor
	, m.MoodyCashFlowRating
	, ISNULL(s.MoodyCashFlowRatingAdjusted, m.MoodyCashFlowRatingAdjusted) MoodyCashFlowRatingAdjusted
	, m.MoodyFacilityRating, m.MoodyRecovery, m.SnPIssuerRating, m.SnPIssuerRatingAdjusted
	, m.SnPFacilityRating, m.SnPfacilityRatingAdjusted, m.SnPRecoveryRating, m.MoodyOutlook, m.MoodyWatch
	, m.SnPWatch, CONVERT(VARCHAR(10), m.NextReportingDate, 101) NextReportingDate
	, CONVERT(VARCHAR(10), m.FiscalYearEndDate, 101) FiscalYearEndDate, c.CalculationId, c.YieldBid
	, c.YieldOffer, CAST(c.YieldMid AS NUMERIC(20, 2)) YieldMid
	, CAST(c.CappedYieldBid AS NUMERIC(20, 2)) CappedYieldBid
	, CAST(c.CappedYieldOffer AS NUMERIC(20, 2)) CappedYieldOffer
	, CAST(c.CappedYieldMid AS NUMERIC(20, 2)) CappedYieldMid
	, CAST(c.TargetYieldBid AS NUMERIC(20, 2)) TargetYieldBid
	, CAST(c.TargetYieldOffer AS NUMERIC(20, 2)) TargetYieldOffer
	, CAST(c.TargetYieldMid AS NUMERIC(20, 2)) TargetYieldMid
	, CAST(c.BetterWorseBid AS NUMERIC(20, 2)) BetterWorseBid
	, CAST(c.BetterWorseOffer AS NUMERIC(20, 2)) BetterWorseOffer
	, CAST(c.BetterWorseMid AS NUMERIC(20, 2)) BetterWorseMid
	, CAST(c.TotalCoupon AS NUMERIC(20, 2)) TotalCoupon, CAST(c.WARF AS NUMERIC(20, 2)) WARF
	, CAST(c.WARFRecovery AS NUMERIC(20, 2)) WARFRecovery, CAST(c.Life AS NUMERIC(20, 2)) Life
	, c.DateId CalculationDateId
	, FORMAT(NULLIF((ISNULL(c.TotalPar, 0) + ISNULL(s.TotalAllocation, 0)), 0), '#,###') TotalPar
	, NULLIF((ISNULL(c.TotalPar, 0) + ISNULL(s.TotalAllocation, 0)), 0) TotalParNum
	, (ISNULL(c.TotalPar, 0)) BODTotalPar
	, ISNULL(s.MoodyFacilityRatingAdjusted, c.MoodyFacilityRatingAdjusted) MoodyFacilityRatingAdjusted
	, ISNULL(a.AnalystResearchId, 0) AnalystResearchId, a.CLOAnalyst, a.HFAnalyst
	, CONVERT(VARCHAR(10), a.AsOfDate, 101) AsOfDate, a.CreditScore, a.LiquidityScore
	, a.OneLLeverage, CONVERT(VARCHAR, CAST(a.TotalLeverage AS MONEY), 1) TotalLeverage
	, CONVERT(VARCHAR, CAST(a.EVMultiple AS MONEY), 1) EVMultiple
	, CONVERT(VARCHAR, CAST(a.LTMRevenues AS MONEY), 1) LTMRevenues
	, CONVERT(VARCHAR, CAST(a.LTMEBITDA AS MONEY), 1) LTMEBITDA
	, CONVERT(VARCHAR, CAST(a.FCF AS MONEY), 1) FCF, CAST(a.LTMFCF AS MONEY) LTMFCF
	, CAST(a.EnterpriseValue AS MONEY) EnterpriseValue, CAST(a.SeniorLeverage AS MONEY) SeniorLeverage, a.Comments
	, a.BusinessDescription, a.AgentBank, cfra.Rank MoodyCashFlowRatingAdjustedRank
	, fra.Rank MoodyFacilityRatingAdjustedRank, s.MaturityDate SecurityMaturityDate
	, CASE WHEN s.MaturityDate IS NOT NULL THEN DATEDIFF(DAY, GETDATE(), s.MaturityDate) ELSE NULL END MaturityDays
	, s.WALifeAdjustment, s.TradePrice, CAST(0 AS BIT) AS IsOnAlert, ISNULL(s.IsStale, 0) IsStale
	, NULL AS SearchText
	, ROW_NUMBER() OVER (PARTITION BY p.PositionId, p.FundId, p.SecurityId ORDER BY p.DateId DESC) AS POSROWNUM
	, cs.ScoreDescription
	, a.Sponsor
	, MatrixImpliedSpread = c.MatrixImpliedSpread
	, DifferentialSpread = ISNULL(c.MatrixImpliedSpread,0)-(m.Spread)
FROM CLO.vw_SecurityFund s
	LEFT JOIN prev_position p WITH (NOLOCK)
	ON s.SecurityId = p.SecurityId AND s.FundId = p.FundId AND ISNULL(s.IsStale, 0) = ISNULL(p.IsStale, 0)
	LEFT JOIN CLO.Country country WITH (NOLOCK)
	ON country.CountryId = p.CountryId
	LEFT JOIN CLO.vw_MarketData m WITH (NOLOCK)
	ON s.SecurityId = m.SecurityId AND s.FundId = m.FundId
	LEFT JOIN CLO.vw_PrevDayMarketData pm WITH (NOLOCK)
	ON s.SecurityId = pm.SecurityId AND s.FundId = pm.FundId
	LEFT JOIN CLO.vw_CurrentAnalystResearch a WITH (NOLOCK)
	ON a.IssuerId = s.IssuerId
	LEFT JOIN CLO.vw_Calculation c WITH (NOLOCK)
	ON s.SecurityId = c.SecurityId AND s.FundId = c.FundId
	LEFT JOIN CLO.Rating cfra WITH (NOLOCK)
	ON cfra.RatingDesc = ISNULL(s.MoodyCashFlowRatingAdjusted, m.MoodyCashFlowRatingAdjusted)
	LEFT JOIN CLO.Rating fra WITH (NOLOCK)
	ON fra.RatingDesc = ISNULL(s.MoodyFacilityRatingAdjusted, c.MoodyFacilityRatingAdjusted)
	LEFT OUTER JOIN CLO.CreditScore cs
	ON CAST(a.CreditScore AS INT) = cs.Id;
GO


GO
ALTER TABLE [CLO].[AggregatedPosition]
    ADD [zSnPAssetRecoveryRating] VARCHAR (2) NULL;


GO
PRINT N'Refreshing [CLO].[vw_AggregatePosition]...';


GO
EXECUTE sp_refreshsqlmodule N'[CLO].[vw_AggregatePosition]';


GO
PRINT N'Altering [CLO].[spGenerateAggregatedPositions]...';


GO
ALTER PROCEDURE [CLO].[spGenerateAggregatedPositions]
AS

delete from CLO.AggregatedPosition where PositionDateId = CLO.GetPrevDayDateId()

SELECT SecurityId, [CLO-1], [CLO-2], [CLO-3], [CLO-4], [CLO-5], [CLO-6], [CLO-7]
into #PivotedMatrixImpliedSpread

FROM (SELECT c.[MatrixImpliedSpread], f.FundCode, c.SecurityId
			FROM CLO.vw_Calculation c WITH (NOLOCK)
			JOIN CLO.Fund f WITH(NOLOCK) ON f.FundId = c.FundId
			WHERE c.DateId = CLO.GetPrevDayDateId()
			) AS s PIVOT
(MAX([MatrixImpliedSpread]) FOR FundCode IN ([CLO-1], [CLO-2], [CLO-3], [CLO-4], [CLO-5], [CLO-6], [CLO-7]) )AS pvt


SELECT SecurityId, [CLO-1], [CLO-2], [CLO-3], [CLO-4], [CLO-5], [CLO-6], [CLO-7]
into #PivotedMatrixWarfRecovery
FROM (SELECT c.MatrixWARFRecovery, f.FundCode, c.SecurityId
			FROM CLO.vw_Calculation c WITH (NOLOCK)
			JOIN CLO.Fund f WITH(NOLOCK) ON f.FundId = c.FundId
			WHERE c.DateId = CLO.GetPrevDayDateId()
			) AS s PIVOT
(MAX(MatrixWARFRecovery) FOR FundCode IN ([CLO-1], [CLO-2], [CLO-3], [CLO-4], [CLO-5], [CLO-6], [CLO-7]) )AS pvt






		;WITH wsodata AS
		(
			SELECT SecurityID AS SecurityCode, MIN(BankDeal_GlobalAmount) AS MinIssueSize, MAX(BankDeal_GlobalAmount) AS MaxIssueSize
			FROM CLO.WsoExtractAssets
			WHERE DateId = [CLO].[GetPrevDayDateId]()
			GROUP BY SecurityID
		),
		loancontract AS
		(
			SELECT SecurityCode, AVG(C.GlobalAmount) AS Average, MIN(C.GlobalAmount) MinAmt, MAX(C.GlobalAmount) AS MaxAmt
			FROM (
			SELECT AssetLoanXIDAssetIDName AS SecurityCode, F.FundId, SUM(C.ContractGlobalAmount) AS GlobalAmount FROM CLO.LoanContract C INNER JOIN Yoda.CLO.Fund F
			ON F.PortfolioName = C.PortfolioName
			WHERE C.AsOfDate = DataMarts.dbo.GetDateFromDateId(Yoda.CLO.GetPrevDayDateId())
			GROUP BY C.AssetLoanXIDAssetIDName, F.FundId) C
			GROUP BY C.SecurityCode
		),
		totalPar AS
		(
			SELECT F.SecurityId, SUM(F.Exposure) AS TotalExposure
			FROM CLO.vw_PositionCountryFund F
			WHERE DateId = CLO.GetPrevDayDateId()
			GROUP BY F.SecurityId
		)

INSERT INTO [CLO].[AggregatedPosition]
           ([PositionDateId]
           ,[CLO1NumExposure]
           ,[CLO2NumExposure]
           ,[CLO3NumExposure]
           ,[CLO4NumExposure]
           ,[CLO5NumExposure]
           ,[CLO6NumExposure]
           ,[CLO7NumExposure]

           ,[CLO1Exposure]
           ,[CLO2Exposure]
           ,[CLO3Exposure]
           ,[CLO4Exposure]
           ,[CLO5Exposure]
           ,[CLO6Exposure]
           ,[CLO7Exposure]

           ,[CLO1PctExposure]
           ,[CLO2PctExposure]
           ,[CLO3PctExposure]
           ,[CLO4PctExposure]
           ,[CLO5PctExposure]
           ,[CLO6PctExposure]
           ,[CLO7PctExposure]

           ,[CLO1TargetPar]
           ,[CLO2TargetPar]
           ,[CLO3TargetPar]
           ,[CLO4TargetPar]
           ,[CLO5TargetPar]
           ,[CLO6TargetPar]
           ,[CLO7TargetPar]

           ,[SecurityId]
           ,[SecurityCode]
           ,[SecurityDesc]
           ,[BBGId]
           ,[Issuer]
           ,[IssuerId]
           ,[IssuerDesc]
           ,[Facility]
           ,[CallDate]
           ,[CountryDesc]
           ,[MaturityDate]
           ,[SnpIndustry]
           ,[MoodyIndustry]

           ,[IsCovLite]
           ,[IsFloating]
           ,[LienType]
           ,[IsOnWatch]
           ,[WatchObjectTypeId]
           ,[WatchObjectId]
           ,[WatchId]
           ,[WatchComments]
           ,[WatchLastUpdatedOn]
           ,[WatchUser]

           ,[SellCandidateObjectTypeId]
           ,[SellCandidateObjectId]
           ,[SellCandidateId]
           ,[SellCandidateComments]
           ,[SellCandidateLastUpdatedOn]
           ,[SellCandidateUser]
           ,[OrigSecurityCode]
           ,[OrigSecurityDesc]
           ,[OrigBBGId]
           ,[OrigIssuer]

           ,[OrigFacility]
           ,[OrigCallDate]
           ,[OrigMaturityDate]
           ,[OrigSnpIndustry]
           ,[OrigMoodyIndustry]
           ,[OrigIsFloating]
           ,[OrigLienType]
           ,[OrigMoodyFacilityRatingAdjusted]
           ,[OrigMoodyCashFlowRatingAdjusted]
           ,[Bid]

           ,[Offer]
           ,[BidNum]
           ,[OfferNum]
           ,[Spread]
           ,[LiborFloor]
           ,[MoodyCashFlowRating]
           ,[MoodyCashFlowRatingAdjusted]
           ,[MoodyFacilityRating]
           ,[MoodyRecovery]
           ,[SnPIssuerRating]
           ,[SnPIssuerRatingAdjusted]
           ,[SnPFacilityRating]
           ,[SnPfacilityRatingAdjusted]
           ,[SnPRecoveryRating]
           ,[MoodyOutlook]

           ,[MoodyWatch]
           ,[SnPWatch]
           ,[NextReportingDate]
           ,[FiscalYearEndDate]
           ,[YieldBid]
           ,[YieldOffer]
           ,[YieldMid]
           ,[CappedYieldBid]
           ,[CappedYieldOffer]
           ,[CappedYieldMid]
           ,[TargetYieldBid]
           ,[TargetYieldOffer]
           ,[TargetYieldMid]
           ,[BetterWorseBid]
           ,[BetterWorseOffer]

           ,[BetterWorseMid]
           ,[TotalCoupon]
           ,[WARF]
           ,[WARFRecovery]
           ,[Life]
           ,[TotalPar]
           ,[TotalParNum]
           ,[BODTotalPar]
           ,[MoodyFacilityRatingAdjusted]
           ,[CLOAnalyst]
           ,[HFAnalyst]
           ,[AsOfDate]
           ,[CreditScore]
           ,[LiquidityScore]
           ,[OneLLeverage]

           ,[TotalLeverage]
           ,[EVMultiple]
           ,[LTMRevenues]
           ,[LTMEBITDA]
           ,[FCF]
           ,[Comments]
           ,[BusinessDescription]
           ,[AgentBank]
           ,[SecurityMaturityDate]
           ,[IsOnAlert]
           ,[LTMFCF]
           ,[EnterpriseValue]
           ,[SeniorLeverage]
           ,[CostPrice]
           ,[CostPriceNum]

           ,[PrevDayBidNum]
           ,[PrevDayOfferNum]
           ,[PrevDayBid]
           ,[PrevDayOffer]
           ,[PriceMove]
           ,[SearchText]
           ,[LienTypeId]
           ,[ScoreDescription]
           ,[GlobalAmount]
		   ,[IsPrivate]
		   ,[Sponsor]

           ,[CLO1MatrixImpliedSpread]
           ,[CLO2MatrixImpliedSpread]
           ,[CLO3MatrixImpliedSpread]
           ,[CLO4MatrixImpliedSpread]
           ,[CLO5MatrixImpliedSpread]
           ,[CLO6MatrixImpliedSpread]

           ,[CLO7MatrixImpliedSpread]
           ,[CLO1DifferentialImpliedSpread]
           ,[CLO2DifferentialImpliedSpread]
           ,[CLO3DifferentialImpliedSpread]
           ,[CLO4DifferentialImpliedSpread]
           ,[CLO5DifferentialImpliedSpread]
           ,[CLO6DifferentialImpliedSpread]
           ,[CLO7DifferentialImpliedSpread]

		   ,[CLO1MatrixWarfRecovery]
		   ,[CLO2MatrixWarfRecovery]
		   ,[CLO3MatrixWarfRecovery]
		   ,[CLO4MatrixWarfRecovery]
		   ,[CLO5MatrixWarfRecovery]
		   ,[CLO6MatrixWarfRecovery]
		   ,[CLO7MatrixWarfRecovery]		   
		   ,[zSnPAssetRecoveryRating]
		   )

SELECT 
		  CLO.GetPrevDayDateId() PositionDateId
		  , NULLIF((ISNULL(MAX(pos.[CLO-1]),0) + ISNULL(MAX(allocation.[CLO-1]),0)),0)	CLO1NumExposure
		  , NULLIF((ISNULL(MAX(pos.[CLO-2]),0) + ISNULL(MAX(allocation.[CLO-2]),0)),0)	CLO2NumExposure
		  , NULLIF((ISNULL(MAX(pos.[CLO-3]),0) + ISNULL(MAX(allocation.[CLO-3]),0)),0)	CLO3NumExposure
		  , NULLIF((ISNULL(MAX(pos.[CLO-4]),0) + ISNULL(MAX(allocation.[CLO-4]),0)),0)	CLO4NumExposure
		  , NULLIF((ISNULL(MAX(pos.[CLO-5]),0) + ISNULL(MAX(allocation.[CLO-5]),0)),0)	CLO5NumExposure
		  , NULLIF((ISNULL(MAX(pos.[CLO-6]),0) + ISNULL(MAX(allocation.[CLO-6]),0)),0)	CLO6NumExposure
		  , NULLIF((ISNULL(MAX(pos.[CLO-7]),0) + ISNULL(MAX(allocation.[CLO-7]),0)),0)	CLO7NumExposure

		  , FORMAT(NULLIF((ISNULL(MAX(pos.[CLO-1]),0) + ISNULL(MAX(allocation.[CLO-1]),0)),0), '#,###')	CLO1Exposure
		  , FORMAT(NULLIF((ISNULL(MAX(pos.[CLO-2]),0) + ISNULL(MAX(allocation.[CLO-2]),0)),0), '#,###')	CLO2Exposure
		  , FORMAT(NULLIF((ISNULL(MAX(pos.[CLO-3]),0) + ISNULL(MAX(allocation.[CLO-3]),0)),0), '#,###')	CLO3Exposure
		  , FORMAT(NULLIF((ISNULL(MAX(pos.[CLO-4]),0) + ISNULL(MAX(allocation.[CLO-4]),0)),0), '#,###')	CLO4Exposure
		  , FORMAT(NULLIF((ISNULL(MAX(pos.[CLO-5]),0) + ISNULL(MAX(allocation.[CLO-5]),0)),0), '#,###')	CLO5Exposure
		  , FORMAT(NULLIF((ISNULL(MAX(pos.[CLO-6]),0) + ISNULL(MAX(allocation.[CLO-6]),0)),0), '#,###')	CLO6Exposure
		  , FORMAT(NULLIF((ISNULL(MAX(pos.[CLO-7]),0) + ISNULL(MAX(allocation.[CLO-7]),0)),0), '#,###')	CLO7Exposure

		  , FORMAT(((ISNULL(MAX(pos.[CLO-1]),0) + ISNULL(MAX(allocation.[CLO-1]),0))/ISNULL(MAX(targetPar.[CLO-1]),1)) , 'p')  CLO1PctExposure   
		  , FORMAT(((ISNULL(MAX(pos.[CLO-2]),0) + ISNULL(MAX(allocation.[CLO-2]),0))/ISNULL(MAX(targetPar.[CLO-2]),1)) , 'p')  CLO2PctExposure 
		  , FORMAT(((ISNULL(MAX(pos.[CLO-3]),0) + ISNULL(MAX(allocation.[CLO-3]),0))/ISNULL(MAX(targetPar.[CLO-3]),1)) , 'p')  CLO3PctExposure 
		  , FORMAT(((ISNULL(MAX(pos.[CLO-4]),0) + ISNULL(MAX(allocation.[CLO-4]),0))/ISNULL(MAX(targetPar.[CLO-4]),1)) , 'p')  CLO4PctExposure 
		  , FORMAT(((ISNULL(MAX(pos.[CLO-5]),0) + ISNULL(MAX(allocation.[CLO-5]),0))/ISNULL(MAX(targetPar.[CLO-5]),1)) , 'p')  CLO5PctExposure
		  , FORMAT(((ISNULL(MAX(pos.[CLO-6]),0) + ISNULL(MAX(allocation.[CLO-6]),0))/ISNULL(MAX(targetPar.[CLO-6]),1)) , 'p')  CLO6PctExposure
		  , FORMAT(((ISNULL(MAX(pos.[CLO-7]),0) + ISNULL(MAX(allocation.[CLO-7]),0))/ISNULL(MAX(targetPar.[CLO-7]),1)) , 'p')  CLO7PctExposure

		  , MAX(targetPar.[CLO-1]) CLO1TargetPar
		  , MAX(targetPar.[CLO-2]) CLO2TargetPar
		  , MAX(targetPar.[CLO-3]) CLO3TargetPar
		  , MAX(targetPar.[CLO-4]) CLO4TargetPar
		  , MAX(targetPar.[CLO-5]) CLO5TargetPar
		  , MAX(targetPar.[CLO-6]) CLO6TargetPar
		  , MAX(targetPar.[CLO-7]) CLO7TargetPar

		  , s.SecurityId
		  , MAX(s.SecurityCode		)		SecurityCode
		  , MAX(s.SecurityDesc		)		SecurityDesc
		  , MAX(s.BBGId			)		BBGId
		  , MAX(s.Issuer			)		Issuer
		  , MAX(s.IssuerId			)		IssuerId
		  , MAX(s.IssuerDesc			)	IssuerDesc
		  , MAX(LTRIM(s.Facility)) Facility
		  , MAX(CASE WHEN s.CallDate <> '1900-01-01' THEN  CONVERT(VARCHAR(10), s.CallDate, 101) ELSE NULL END) CallDate
		  , COALESCE(MAX(country.[CLO-1]), MAX(country.[CLO-2]), MAX(country.[CLO-3]), MAX(country.[CLO-4]), MAX(country.[CLO-5]), MAX(country.[CLO-6]), MAX(country.[CLO-7]))  CountryDesc
		  , MAX(CONVERT(VARCHAR(10), s.MaturityDate, 101)) MaturityDate
		  , MAX(s.SnpIndustry)				SnpIndustry
		  , MAX(s.MoodyIndustry)			MoodyIndustry

		  , COALESCE(MAX(covlite.[CLO-1]), MAX(covlite.[CLO-2]), MAX(covlite.[CLO-3]), MAX(covlite.[CLO-4]), MAX(covlite.[CLO-5]), MAX(covlite.[CLO-6]), MAX(covlite.[CLO-7]))  IsCovLite
		  , MAX(CASE WHEN (s.IsFloating = 1) THEN 'Floating' ELSE 'Fixed' END) IsFloating
		  , MAX(s.LienType						)		LienType
		  , s.IsOnWatch					
		  , MAX(s.WatchObjectTypeId				)		WatchObjectTypeId
		  , MAX(s.WatchObjectId					)		WatchObjectId					
		  , MAX(s.WatchId						)		WatchId						
		  , MAX(s.WatchComments				)		WatchComments				
		  , MAX(s.WatchLastUpdatedOn				)		WatchLastUpdatedOn				
		  , MAX(s.WatchUser						)		WatchUser						

		  , MAX(s.SellCandidateObjectTypeId) SellCandidateObjectTypeId
		  , MAX(s.SellCandidateObjectId) SellCandidateObjectId					
		  , MAX(s.SellCandidateId) SellCandidateId						
		  , MAX(s.SellCandidateComments) SellCandidateComments				
		  , MAX(s.SellCandidateLastUpdatedOn) SellCandidateLastUpdatedOn				
		  , MAX(s.SellCandidateUser) SellCandidateUser						
		  , MAX(s.OrigSecurityCode				)		OrigSecurityCode				
		  , MAX(s.OrigSecurityDesc				)		OrigSecurityDesc				
		  , MAX(s.OrigBBGId					)		OrigBBGId					
		  , MAX(s.OrigIssuer					)		OrigIssuer		
		  
		  , MAX(s.OrigFacility					)		OrigFacility					
		  , MAX(s.OrigCallDate 				)		OrigCallDate 				
		  , MAX(s.OrigMaturityDate				)		OrigMaturityDate				
		  , MAX(s.OrigSnpIndustry				)		OrigSnpIndustry				
		  , MAX(s.OrigMoodyIndustry			)		OrigMoodyIndustry			
		  , MAX(s.OrigIsFloating 				)		OrigIsFloating 				
		  , MAX(s.OrigLienType					)		OrigLienType					
		  , MAX(c.MoodyFacilityRatingAdjusted	)	AS OrigMoodyFacilityRatingAdjusted
		  , MAX(m.MoodyCashFlowRatingAdjusted	)	AS OrigMoodyCashFlowRatingAdjusted
		  , CONVERT(VARCHAR, CAST(AVG(m.Bid) AS MONEY),1)  Bid

		  , CONVERT(VARCHAR, CAST(AVG(m.Offer)AS MONEY),1) Offer
		  , MAX(m.Bid) BidNum
		  , MAX(m.Offer) OfferNum
		  , CAST(MAX(m.Spread) AS NUMERIC(20,2)) Spread	
		  , CAST(MAX(m.LiborFloor) AS NUMERIC(20,2))	LiborFloor
		  , MAX(m.MoodyCashFlowRating) MoodyCashFlowRating
		  , ISNULL(MAX(s.MoodyCashFlowRatingAdjusted), MAX(m.MoodyCashFlowRatingAdjusted)) MoodyCashFlowRatingAdjusted
		  , MAX(m.MoodyFacilityRating)		MoodyFacilityRating
		  , MAX(m.MoodyRecovery				)		MoodyRecovery
		  , MAX(m.SnPIssuerRating				)		SnPIssuerRating				
		  , MAX(m.SnPIssuerRatingAdjusted		)		SnPIssuerRatingAdjusted		
		  , MAX(m.SnPFacilityRating			)		SnPFacilityRating			
		  , MAX(m.SnPfacilityRatingAdjusted	)		SnPfacilityRatingAdjusted	
		  , MAX(m.SnPRecoveryRating			)		SnPRecoveryRating			
		  , MAX(m.MoodyOutlook					)		MoodyOutlook					

		  , MAX(m.MoodyWatch					)		MoodyWatch					
		  , MAX(m.SnPWatch						)		SnPWatch						
		  , CONVERT(VARCHAR(10), MAX(m.NextReportingDate), 101) NextReportingDate
		  , CONVERT(VARCHAR(10), MAX(m.FiscalYearEndDate), 101) FiscalYearEndDate
		  , CAST(AVG(c.YieldBid			)AS NUMERIC(20,2))			YieldBid				
		  , CAST(AVG(c.YieldOffer			)AS NUMERIC(20,2))			YieldOffer			
		  , CAST(AVG(c.YieldMid			)AS NUMERIC(20,2))			YieldMid				
		  , CAST(AVG(c.CappedYieldBid		)AS NUMERIC(20,2))			CappedYieldBid		
		  , CAST(AVG(c.CappedYieldOffer	)AS NUMERIC(20,2))			CappedYieldOffer		
		  , CAST(AVG(c.CappedYieldMid		)AS NUMERIC(20,2))			CappedYieldMid		
		  , CAST(AVG(c.TargetYieldBid		)AS NUMERIC(20,2))			TargetYieldBid		
		  , CAST(AVG(c.TargetYieldOffer	)AS NUMERIC(20,2))			TargetYieldOffer		
		  , CAST(AVG(c.TargetYieldMid		)AS NUMERIC(20,2))			TargetYieldMid		
		  , CAST(AVG(c.BetterWorseBid		)AS NUMERIC(20,2))			BetterWorseBid		
		  , CAST(AVG(c.BetterWorseOffer	)AS NUMERIC(20,2))			BetterWorseOffer		

		  , CAST(AVG(c.BetterWorseMid		)AS NUMERIC(20,2))			BetterWorseMid		
		  , CAST(AVG(c.TotalCoupon			)AS NUMERIC(20,2))			TotalCoupon			
		  , CAST(AVG(c.WARF				)AS NUMERIC(20,2))			WARF					
		  , CAST(AVG(c.WARFRecovery		)AS NUMERIC(20,2))			WARFRecovery			
		  , CAST(AVG(c.Life				)AS NUMERIC(20,2))			Life
		  , FORMAT(NULLIF(ISNULL(MAX(TP.TotalExposure), 0),0), '#,###') TotalPar
		  , ISNULL(MAX(TP.TotalExposure), 0) TotalParNum
		  , (ISNULL(MAX(c.TotalPar),0)) BODTotalPar
		  , ISNULL(MAX(s.MoodyFacilityRatingAdjusted),  MAX(c.MoodyFacilityRatingAdjusted)) MoodyFacilityRatingAdjusted
		  , MAX(a.CLOAnalyst)			CLOAnalyst
		  , MAX(a.HFAnalyst)				HFAnalyst
		  , CONVERT(VARCHAR(10), MAX(a.AsOfDate), 101) AsOfDate
		  , MAX(a.CreditScore)	CreditScore	
		  , MAX(a.LiquidityScore)	LiquidityScore		
		  , MAX(a.OneLLeverage)	OneLLeverage		

		  , CONVERT(VARCHAR, CAST(MAX(a.TotalLeverage) AS MONEY), 1) TotalLeverage
		  , CONVERT(VARCHAR, CAST(MAX(a.EVMultiple) AS MONEY), 1) EVMultiple
		  , CONVERT(VARCHAR, CAST(MAX(a.LTMRevenues) AS MONEY), 1) LTMRevenues
		  , CONVERT(VARCHAR, CAST(MAX(a.LTMEBITDA )AS MONEY), 1) LTMEBITDA
		  , CONVERT(VARCHAR, CAST(MAX(a.FCF) AS MONEY), 1) FCF
		  , MAX(a.Comments)						Comments	
		  , MAX(a.BusinessDescription)			BusinessDescription	
		  , MAX(a.AgentBank			)			AgentBank			
		  , MAX(s.MaturityDate) SecurityMaturityDate
		  , CAST(0 AS BIT) AS IsOnAlert
		  , CAST(MAX(a.LTMFCF) AS NUMERIC(38,2)) LTMFCF
		  , CAST(MAX(a.EnterpriseValue) AS NUMERIC(10,2)) EnterpriseValue
		  , CAST(MAX(a.SeniorLeverage) AS NUMERIC(10,2)) SeniorLeverage
		  , CONVERT(VARCHAR, CAST(MAX(m.CostPrice) AS MONEY), 1) CostPrice
		  , MAX(m.CostPrice) CostPriceNum

		  , MAX(pm.Bid)	PrevDayBidNum
		  , MAX(pm.Offer)	PrevDayOfferNum
		  , CONVERT(VARCHAR, CAST(MAX(pm.Bid) AS MONEY), 1) PrevDayBid
		  , CONVERT(VARCHAR, CAST(MAX(pm.Offer) AS MONEY), 1) PrevDayOffer
		  , CASE WHEN ISNULL(MAX(m.Bid),0) <> 0 AND ISNULL(MAX(pm.Bid),0) <> 0 THEN (MAX(m.Bid) - MAX(pm.Bid)) ELSE NULL END PriceMove
		  , NULL AS SearchText
		  , MAX(s.LienTypeId) LienTypeId
		  , MAX(cs.ScoreDescription) ScoreDescription
		  , ISNULL(MAX(lc.MaxAmt), MAX(wso.MaxIssueSize)) GlobalAmount
		  , a.IsPrivate
		  , a.Sponsor
		  , CAST(ISNULL(MAX(matrix.[CLO-1]),0) as decimal(28,2)) CLO1MatrixImpliedSpread
		  , CAST(ISNULL(MAX(matrix.[CLO-2]),0) as decimal(28,2)) CLO2MatrixImpliedSpread
		  , CAST(ISNULL(MAX(matrix.[CLO-3]),0) as decimal(28,2)) CLO3MatrixImpliedSpread
		  , CAST(ISNULL(MAX(matrix.[CLO-4]),0) as decimal(28,2)) CLO4MatrixImpliedSpread
		  , CAST(ISNULL(MAX(matrix.[CLO-5]),0) as decimal(28,2)) CLO5MatrixImpliedSpread
		  , CAST(ISNULL(MAX(matrix.[CLO-6]),0) as decimal(28,2)) CLO6MatrixImpliedSpread
		  , CAST(ISNULL(MAX(matrix.[CLO-7]),0) as decimal(28,2)) CLO7MatrixImpliedSpread
		  , CLO1DifferentialImpliedSpread = CAST( ISNULL(MAX(m.Spread),0) - ISNULL(MAX(matrix.[CLO-1]),0)   as decimal(28,2))
		  , CLO2DifferentialImpliedSpread = CAST( ISNULL(MAX(m.Spread),0) - ISNULL(MAX(matrix.[CLO-2]),0)   as decimal(28,2))
		  , CLO3DifferentialImpliedSpread = CAST( ISNULL(MAX(m.Spread),0) - ISNULL(MAX(matrix.[CLO-3]),0)   as decimal(28,2))
		  , CLO4DifferentialImpliedSpread = CAST( ISNULL(MAX(m.Spread),0) - ISNULL(MAX(matrix.[CLO-4]),0)   as decimal(28,2))
		  , CLO5DifferentialImpliedSpread = CAST( ISNULL(MAX(m.Spread),0) - ISNULL(MAX(matrix.[CLO-5]),0)   as decimal(28,2))
		  , CLO6DifferentialImpliedSpread = CAST( ISNULL(MAX(m.Spread),0) - ISNULL(MAX(matrix.[CLO-6]),0)   as decimal(28,2))
		  , CLO7DifferentialImpliedSpread = CAST( ISNULL(MAX(m.Spread),0) - ISNULL(MAX(matrix.[CLO-7]),0)   as decimal(28,2))

		  , CAST(ISNULL(MAX(matrixwarfrecovery.[CLO-1]),0) as decimal(28,2)) CLO1MatrixWarfRecovery
		  , CAST(ISNULL(MAX(matrixwarfrecovery.[CLO-2]),0) as decimal(28,2)) CLO2MatrixWarfRecovery
		  , CAST(ISNULL(MAX(matrixwarfrecovery.[CLO-3]),0) as decimal(28,2)) CLO3MatrixWarfRecovery
		  , CAST(ISNULL(MAX(matrixwarfrecovery.[CLO-4]),0) as decimal(28,2)) CLO4MatrixWarfRecovery
		  , CAST(ISNULL(MAX(matrixwarfrecovery.[CLO-5]),0) as decimal(28,2)) CLO5MatrixWarfRecovery
		  , CAST(ISNULL(MAX(matrixwarfrecovery.[CLO-6]),0) as decimal(28,2)) CLO6MatrixWarfRecovery
		  , CAST(ISNULL(MAX(matrixwarfrecovery.[CLO-7]),0) as decimal(28,2)) CLO7MatrixWarfRecovery
		  , MAX(c.zSnPAssetRecoveryRating)
    FROM  CLO.vw_Security s  WITH (NOLOCK)
	      LEFT  JOIN CLO.vw_SecurityMarket m WITH (NOLOCK) ON s.SecurityId			= m.SecurityId 
		  LEFT  JOIN CLO.vw_PrevDaySecurityMarket pm WITH (NOLOCK) ON s.SecurityId	= pm.SecurityId 
		  LEFT  JOIN CLO.vw_CurrentAnalystResearch a WITH (NOLOCK) ON a.IssuerId	= s.IssuerId
		  LEFT  JOIN CLO.vw_Calculation c WITH (NOLOCK) ON s.SecurityId			= c.SecurityId 
		  LEFT	JOIN CLO.Rating cfra WITH(NOLOCK) ON cfra.RatingDesc			= ISNULL(s.MoodyCashFlowRatingAdjusted, m.MoodyCashFlowRatingAdjusted)
		  LEFT	JOIN CLO.Rating fra WITH(NOLOCK) ON fra.RatingDesc				= ISNULL(s.MoodyFacilityRatingAdjusted,  c.MoodyFacilityRatingAdjusted)
		  LEFT  JOIN CLO.vw_PivotedPositionExposure		pos  WITH (NOLOCK) ON pos.SecurityId = s.SecurityId
		  LEFT  JOIN CLO.vw_PivotedPositionCountry		country  WITH (NOLOCK) ON country.SecurityId = s.SecurityId
		  LEFT  JOIN CLO.vw_PivotedPositionIsCovLite	covlite  WITH (NOLOCK) ON covlite.SecurityId = s.SecurityId
		  LEFT  JOIN CLO.vw_PivotedTradeAllocation	allocation  WITH (NOLOCK) ON allocation.SecurityId = s.SecurityId
		  LEFT  JOIN CLO.#PivotedMatrixImpliedSpread	matrix  WITH (NOLOCK) ON matrix.SecurityId = s.SecurityId
		  LEFT  JOIN CLO.#PivotedMatrixWarfRecovery		matrixwarfrecovery  WITH (NOLOCK) ON matrixwarfrecovery.SecurityId = s.SecurityId

		  LEFT OUTER JOIN CLO.CreditScore cs ON CAST(a.CreditScore AS INT) = cs.Id
		  LEFT OUTER JOIN wsodata wso ON wso.SecurityCode = s.SecurityCode
		  LEFT OUTER JOIN loancontract lc ON lc.SecurityCode = s.SecurityCode
		  LEFT OUTER JOIN totalPar TP ON TP.SecurityId = s.SecurityId
		  CROSS JOIN CLO.vw_PivotedFundTargetPar	targetpar
	GROUP BY S.SecurityId,s.IsOnWatch, a.IsPrivate, a.Sponsor
	

	drop table #PivotedMatrixImpliedSpread
	drop table #PivotedMatrixWarfRecovery

RETURN 0
GO
PRINT N'Refreshing [CLO].[spCalculateSummaryData]...';


GO
EXECUTE sp_refreshsqlmodule N'[CLO].[spCalculateSummaryData]';


GO
PRINT N'Refreshing [CLO].[spGetRatingsChange]...';


GO
EXECUTE sp_refreshsqlmodule N'[CLO].[spGetRatingsChange]';


GO
PRINT N'Refreshing [YDA].[CloGetAllAggPositions]...';


GO
EXECUTE sp_refreshsqlmodule N'[YDA].[CloGetAllAggPositions]';


GO
PRINT N'Refreshing [CLO].[sp_GetExcelPluginData]...';


GO
EXECUTE sp_refreshsqlmodule N'[CLO].[sp_GetExcelPluginData]';


GO
PRINT N'Refreshing [CLO].[spGetAllPositionForSecurities]...';


GO
EXECUTE sp_refreshsqlmodule N'[CLO].[spGetAllPositionForSecurities]';


GO
PRINT N'Refreshing [CLO].[spGetAllPositions]...';


GO
EXECUTE sp_refreshsqlmodule N'[CLO].[spGetAllPositions]';


GO
PRINT N'Refreshing [CLO].[spPositionSizeByCreditScoreByTotalCouponRuleProcessor]...';


GO
EXECUTE sp_refreshsqlmodule N'[CLO].[spPositionSizeByCreditScoreByTotalCouponRuleProcessor]';


GO
PRINT N'Refreshing [CLO].[spTop10Bottom10Movers]...';


GO
EXECUTE sp_refreshsqlmodule N'[CLO].[spTop10Bottom10Movers]';


GO
PRINT N'Update complete.';


GO



GO
ALTER VIEW CLO.vw_AggregatePosition
AS
	SELECT [PositionDateId]
      ,[CLO1NumExposure]
      ,[CLO2NumExposure]
      ,[CLO3NumExposure]
      ,[CLO4NumExposure]
      ,[CLO5NumExposure]
      ,[CLO6NumExposure]
      ,[CLO7NumExposure]
      ,[CLO1Exposure]
      ,[CLO2Exposure]
      ,[CLO3Exposure]
      ,[CLO4Exposure]
      ,[CLO5Exposure]
      ,[CLO6Exposure]
      ,[CLO7Exposure]
      ,[CLO1PctExposure]
      ,[CLO2PctExposure]
      ,[CLO3PctExposure]
      ,[CLO4PctExposure]
      ,[CLO5PctExposure]
      ,[CLO6PctExposure]
      ,[CLO7PctExposure]
      ,[CLO1TargetPar]
      ,[CLO2TargetPar]
      ,[CLO3TargetPar]
      ,[CLO4TargetPar]
      ,[CLO5TargetPar]
      ,[CLO6TargetPar]
      ,[CLO7TargetPar]
      ,[SecurityId]
      ,[SecurityCode]
      ,[SecurityDesc]
      ,[BBGId]
      ,[Issuer]
      ,[IssuerId]
      ,[IssuerDesc]
      ,[Facility]
      ,[CallDate]
      ,[CountryDesc]
      ,[MaturityDate]
      ,[SnpIndustry]
      ,[MoodyIndustry]
      ,[IsCovLite]
      ,[IsFloating]
      ,[LienType]
      ,[IsOnWatch]
      ,[WatchObjectTypeId]
      ,[WatchObjectId]
      ,[WatchId]
      ,[WatchComments]
      ,[WatchLastUpdatedOn]
      ,[WatchUser]
      ,[SellCandidateObjectTypeId]
      ,[SellCandidateObjectId]
      ,[SellCandidateId]
      ,[SellCandidateComments]
      ,[SellCandidateLastUpdatedOn]
      ,[SellCandidateUser]
      ,[OrigSecurityCode]
      ,[OrigSecurityDesc]
      ,[OrigBBGId]
      ,[OrigIssuer]
      ,[OrigFacility]
      ,[OrigCallDate]
      ,[OrigMaturityDate]
      ,[OrigSnpIndustry]
      ,[OrigMoodyIndustry]
      ,[OrigIsFloating]
      ,[OrigLienType]
      ,[OrigMoodyFacilityRatingAdjusted]
      ,[OrigMoodyCashFlowRatingAdjusted]
      ,[Bid]
      ,[Offer]
      ,[BidNum]
      ,[OfferNum]
      ,[Spread]
      ,[LiborFloor]
      ,[MoodyCashFlowRating]
      ,[MoodyCashFlowRatingAdjusted]
      ,[MoodyFacilityRating]
      ,[MoodyRecovery]
      ,[SnPIssuerRating]
      ,[SnPIssuerRatingAdjusted]
      ,[SnPFacilityRating]
      ,[SnPfacilityRatingAdjusted]
      ,[SnPRecoveryRating]
      ,[MoodyOutlook]
      ,[MoodyWatch]
      ,[SnPWatch]
      ,[NextReportingDate]
      ,[FiscalYearEndDate]
      ,[YieldBid]
      ,[YieldOffer]
      ,[YieldMid]
      ,[CappedYieldBid]
      ,[CappedYieldOffer]
      ,[CappedYieldMid]
      ,[TargetYieldBid]
      ,[TargetYieldOffer]
      ,[TargetYieldMid]
      ,[BetterWorseBid]
      ,[BetterWorseOffer]
      ,[BetterWorseMid]
      ,[TotalCoupon]
      ,[WARF]
      ,[WARFRecovery]
      ,[Life]
      ,[TotalPar]
      ,[TotalParNum]
      ,[BODTotalPar]
      ,[MoodyFacilityRatingAdjusted]
      ,[CLOAnalyst]
      ,[HFAnalyst]
      ,[AsOfDate]
      ,[CreditScore]
      ,[LiquidityScore]
      ,[OneLLeverage]
      ,[TotalLeverage]
      ,[EVMultiple]
      ,[LTMRevenues]
      ,[LTMEBITDA]
      ,[FCF]
      ,[Comments]
      ,[BusinessDescription]
      ,[AgentBank]
      ,[SecurityMaturityDate]
      ,[IsOnAlert]
      ,[LTMFCF]
      ,[EnterpriseValue]
      ,[SeniorLeverage]
      ,[CostPrice]
      ,[CostPriceNum]
      ,[PrevDayBidNum]
      ,[PrevDayOfferNum]
      ,[PrevDayBid]
      ,[PrevDayOffer]
      ,[PriceMove]
      ,[SearchText]
      ,[LienTypeId]
      ,[ScoreDescription]
      ,[GlobalAmount]
      ,[IsPrivate]
      ,[Sponsor]
      ,[CLO1MatrixImpliedSpread]
      ,[CLO2MatrixImpliedSpread]
      ,[CLO3MatrixImpliedSpread]
      ,[CLO4MatrixImpliedSpread]
      ,[CLO5MatrixImpliedSpread]
      ,[CLO6MatrixImpliedSpread]
      ,[CLO7MatrixImpliedSpread]
      ,[CLO1DifferentialImpliedSpread]
      ,[CLO2DifferentialImpliedSpread]
      ,[CLO3DifferentialImpliedSpread]
      ,[CLO4DifferentialImpliedSpread]
      ,[CLO5DifferentialImpliedSpread]
      ,[CLO6DifferentialImpliedSpread]
      ,[CLO7DifferentialImpliedSpread] 
	  ,[CLO1MatrixWarfRecovery]
      ,[CLO2MatrixWarfRecovery]
      ,[CLO3MatrixWarfRecovery]
      ,[CLO4MatrixWarfRecovery]
      ,[CLO5MatrixWarfRecovery]
      ,[CLO6MatrixWarfRecovery]
      ,[CLO7MatrixWarfRecovery]
	  ,zSnPAssetRecoveryRating
	  FROM CLO.AggregatedPosition 

	  WHERE 

	  PositionDateId = CLO.GetPrevDayDateId()
GO
PRINT N'Refreshing [YDA].[CloGetAllAggPositions]...';


GO
EXECUTE sp_refreshsqlmodule N'[YDA].[CloGetAllAggPositions]';


GO
PRINT N'Refreshing [CLO].[sp_GetExcelPluginData]...';


GO
EXECUTE sp_refreshsqlmodule N'[CLO].[sp_GetExcelPluginData]';


GO
PRINT N'Refreshing [CLO].[spGetAllPositionForSecurities]...';


GO
EXECUTE sp_refreshsqlmodule N'[CLO].[spGetAllPositionForSecurities]';


GO
PRINT N'Refreshing [CLO].[spGetAllPositions]...';


GO
EXECUTE sp_refreshsqlmodule N'[CLO].[spGetAllPositions]';


GO
PRINT N'Refreshing [CLO].[spPositionSizeByCreditScoreByTotalCouponRuleProcessor]...';


GO
EXECUTE sp_refreshsqlmodule N'[CLO].[spPositionSizeByCreditScoreByTotalCouponRuleProcessor]';


GO
PRINT N'Refreshing [CLO].[spTop10Bottom10Movers]...';


GO
EXECUTE sp_refreshsqlmodule N'[CLO].[spTop10Bottom10Movers]';


GO
PRINT N'Update complete.';


GO
GO
ALTER PROCEDURE [YDA].[CloGetAllAggPositions]
	 @OnlyWithExposures VARCHAR(3),
	 @cachelocation VARCHAR(50)
AS
	Select
		[LOANX] = ''
		,[BBG ID] = ''
		,[ISSUER] = ''
		,[FACILITY] = ''
		,[LIEN TYPE] = ''
		,[TOTAL EXPO] = ''
		,[CLO-1] = ''
		,[CLO-1 %] = ''
		,[CLO-2] = ''
		,[CLO-2 %] = ''
		,[CLO-3] = ''
		,[CLO-3 %] = ''
		,[CLO-4] = ''
		,[CLO-4 %] = ''
		,[CLO-5] = ''
		,[CLO-5 %] = ''
		,[CLO-6] = ''
		,[CLO-6 %] = ''
		,[CLO-7] = ''
		,[CLO-7 %] = ''
		,[CALL DATE] = ''
		,[BID] = ''
		,[OFFER] = ''
		,[SPREAD] = ''
		,[FLOOR] = ''
		,[MOODY'S CFR] = ''
		,[MOODY'S CFR ADJ] = ''
		,[MOODY FACILITY] = ''
		,[MOODY FACILITY ADJ] = ''
		,[MOODY OUTLOOK] = ''
		,[MOODY WATCH] = ''
		,[WARF] = ''
		,[MOODY'S RECOVERY] = ''
		,[WARF RECOVERY] = ''
		,[S&P ISSUER] = ''
		,[S&P ISSUER ADJ] = ''
		,[S&P FACILITY RATING] = ''
		,[S&P WATCH] = ''
		,[MATURITY] = ''
		,[COUNTRY] = ''
		,[FLOAT / FIXED] = ''
		,[MOODY INDUSTRY] = ''
		,[S&P INDUSTRY] = ''
		,[COV LITE (Y/N)] = ''
		,[CLO ANALYST] = ''
		,[OFFER YIELD] = ''
		,[TARGET OFFER YIELD] = ''
		,[OFFER YIELD B/W] = ''
		,[CAPPED OFFER YIELD] = ''
		,[BID YIELD] = ''
		,[TARGET BID YIELD] = ''
		,[CAPPED BID YIELD] = ''
		
		,[BID YIELD B/W] =''
		
		,[MID YIELD] = ''
		,[CAPPED MID YIELD] = ''
		
		,[MID YIELD B/W] =''		
		
		,[AS OF DATE] = ''
		,[1L LEVERAGE] = ''
		,[TOTAL LEVERAGE] = ''
		,[EV MULTIPLE] = ''
		,[LTM REVENUES] = ''
		,[LTM EBITDA] = ''
		,[LTMFCF] = ''
		,[AGENT BANK] = ''
		,[BUSINESS DESCRPTION] = ''
		,[CREDIT SCORE] = ''
		,[NEXT REPORTING] = ''
		,[FISCAL YEAR END] = ''
		,[HF ANALYST] = ''
		,[COMMENTS] = ''
		,[CLO-6 COST PRICE] = ''
		,[CLO-7 COST PRICE] = ''

      , [CLO-1 MATRIX IMPLIED SPREAD]				= ''
      , [CLO-2 MATRIX IMPLIED SPREAD]				= ''
      , [CLO-3 MATRIX IMPLIED SPREAD]				= ''
      , [CLO-4 MATRIX IMPLIED SPREAD]				= ''
      , [CLO-5 MATRIX IMPLIED SPREAD]				= ''
      , [CLO-6 MATRIX IMPLIED SPREAD]				= ''
      , [CLO-7 MATRIX IMPLIED SPREAD]				= ''
      , [CLO-1 DIFFERENTIAL IMPLIED SPREAD]			= ''
      , [CLO-2 DIFFERENTIAL IMPLIED SPREAD]			= ''
      , [CLO-3 DIFFERENTIAL IMPLIED SPREAD]			= ''
      , [CLO-4 DIFFERENTIAL IMPLIED SPREAD]			= ''
      , [CLO-5 DIFFERENTIAL IMPLIED SPREAD]			= ''
      , [CLO-6 DIFFERENTIAL IMPLIED SPREAD]			= ''
      , [CLO-7 DIFFERENTIAL IMPLIED SPREAD] 		= ''
	  , [CLO-1 MATRIX WARF RECOVERY]				= ''
      , [CLO-2 MATRIX WARF RECOVERY]				= ''
      , [CLO-3 MATRIX WARF RECOVERY]				= ''
      , [CLO-4 MATRIX WARF RECOVERY]				= ''
      , [CLO-5 MATRIX WARF RECOVERY]				= ''
      , [CLO-6 MATRIX WARF RECOVERY]				= ''
      , [CLO-7 MATRIX WARF RECOVERY]				= ''
	  , [SNP ASSET RECOVERY]					= ''
		,SortOrder = 0
	into #Results
	UNION
	Select
		[LOANX] = 'LOANX'
		,[BBG ID] = 'BBG ID'
		,[ISSUER] = 'ISSUER'
		,[FACILITY] = 'FACILITY'
		,[LIEN TYPE] = 'LIEN TYPE'
		,[TOTAL EXPO] = 'TOTAL EXPO'
		,[CLO-1] = 'CLO-1'
		,[CLO-1 %] = 'CLO-1 %'
		,[CLO-2] = 'CLO-2'
		,[CLO-2 %] = 'CLO-2 %'
		,[CLO-3] = 'CLO-3'
		,[CLO-3 %] = 'CLO-3 %'
		,[CLO-4] = 'CLO-4'
		,[CLO-4 %] = 'CLO-4 %'
		,[CLO-5] = 'CLO-5'
		,[CLO-5 %] = 'CLO-5 %'
		,[CLO-6] = 'CLO-6'
		,[CLO-6 %] = 'CLO-6 %'
		,[CLO-7] = 'CLO-7'
		,[CLO-7 %] = 'CLO-7 %'
		,[CALL DATE] = 'CALL DATE'
		,[BID] = 'BID'
		,[OFFER] = 'OFFER'
		,[SPREAD] = 'SPREAD'
		,[FLOOR] = 'FLOOR'
		,[MOODY'S CFR] = 'MOODY''S CFR'
		,[MOODY'S CFR ADJ] = 'MOODY''S CFR ADJ'
		,[MOODY FACILITY] = 'MOODY FACILITY'
		,[MOODY FACILITY ADJ] = 'MOODY FACILITY ADJ'
		,[MOODY OUTLOOK] = 'MOODY OUTLOOK'
		,[MOODY WATCH] = 'MOODY WATCH'
		,[WARF] = 'WARF'
		,[MOODY'S RECOVERY] = 'MOODY''S RECOVERY'
		,[WARF RECOVERY] = 'WARF RECOVERY'
		,[S&P ISSUER] = 'S&P ISSUER'
		,[S&P ISSUER ADJ] = 'S&P ISSUER ADJ'
		,[S&P FACILITY RATING] = 'S&P FACILITY RATING'
		,[S&P WATCH] = 'S&P WATCH'
		,[MATURITY] = 'MATURITY'
		,[COUNTRY] = 'COUNTRY'
		,[FLOAT / FIXED] = 'FLOAT / FIXED'
		,[MOODY INDUSTRY] = 'MOODY INDUSTRY'
		,[S&P INDUSTRY] = 'S&P INDUSTRY'
		,[COV LITE (Y/N)] = 'COV LITE (Y/N)'
		,[CLO ANALYST] = 'CLO ANALYST'
		,[OFFER YIELD] = 'OFFER YIELD'
		,[TARGET OFFER YIELD] = 'TARGET OFFER YIELD'
		,[OFFER YIELD B/W] = 'OFFER YIELD B/W'
		,[CAPPED OFFER YIELD] = 'CAPPED OFFER YIELD'
		,[BID YIELD] = 'BID YIELD'
		,[TARGET BID YIELD] = 'TARGET BID YIELD'
		,[CAPPED BID YIELD] = 'CAPPED BID YIELD'
		
		,[BID YIELD B/W] ='BID YIELD B/W'
		
		,[MID YIELD] = 'MID YIELD'
		,[CAPPED MID YIELD] = 'CAPPED MID YIELD'
		
		,[MID YIELD B/W] ='[MID YIELD B/W'
		
		,[AS OF DATE] = 'AS OF DATE'
		,[1L LEVERAGE] = '1L LEVERAGE'
		,[TOTAL LEVERAGE] = 'TOTAL LEVERAGE'
		,[EV MULTIPLE] = 'EV MULTIPLE'
		,[LTM REVENUES] = 'LTM REVENUES'
		,[LTM EBITDA] = 'LTM EBITDA'
		,[LTMFCF] = 'LTMFCF'
		,[AGENT BANK] = 'AGENT BANK'
		,[BUSINESS DESCRPTION] = 'BUSINESS DESCRPTION'
		,[CREDIT SCORE] = 'CREDIT SCORE'
		,[NEXT REPORTING] = 'NEXT REPORTING'
		,[FISCAL YEAR END] = 'FISCAL YEAR END'
		,[HF ANALYST] = 'HF ANALYST'
		,[COMMENTS] = 'COMMENTS'
		,[CLO-6 COST PRICE] = 'CLO-6 COST PRICE'
		,[CLO-7 COST PRICE] = 'CLO-7 COST PRICE'

      , [CLO-1 MATRIX IMPLIED SPREAD]				= 'CLO-1 MATRIX IMPLIED SPREAD'
      , [CLO-2 MATRIX IMPLIED SPREAD]				= 'CLO-2 MATRIX IMPLIED SPREAD'
      , [CLO-3 MATRIX IMPLIED SPREAD]				= 'CLO-3 MATRIX IMPLIED SPREAD'
      , [CLO-4 MATRIX IMPLIED SPREAD]				= 'CLO-4 MATRIX IMPLIED SPREAD'
      , [CLO-5 MATRIX IMPLIED SPREAD]				= 'CLO-5 MATRIX IMPLIED SPREAD'
      , [CLO-6 MATRIX IMPLIED SPREAD]				= 'CLO-6 MATRIX IMPLIED SPREAD'
      , [CLO-7 MATRIX IMPLIED SPREAD]				= 'CLO-7 MATRIX IMPLIED SPREAD'
      , [CLO-1 DIFFERENTIAL IMPLIED SPREAD]			= 'CLO-1 DIFFERENTIAL IMPLIED SPREAD'
      , [CLO-2 DIFFERENTIAL IMPLIED SPREAD]			= 'CLO-2 DIFFERENTIAL IMPLIED SPREAD'
      , [CLO-3 DIFFERENTIAL IMPLIED SPREAD]			= 'CLO-3 DIFFERENTIAL IMPLIED SPREAD'
      , [CLO-4 DIFFERENTIAL IMPLIED SPREAD]			= 'CLO-4 DIFFERENTIAL IMPLIED SPREAD'
      , [CLO-5 DIFFERENTIAL IMPLIED SPREAD]			= 'CLO-5 DIFFERENTIAL IMPLIED SPREAD'
      , [CLO-6 DIFFERENTIAL IMPLIED SPREAD]			= 'CLO-6 DIFFERENTIAL IMPLIED SPREAD'
      , [CLO-7 DIFFERENTIAL IMPLIED SPREAD] 		= 'CLO-7 DIFFERENTIAL IMPLIED SPREAD'
	  , [CLO-1 MATRIX WARF RECOVERY]				= 'CLO-1 MATRIX WARF RECOVERY'
      , [CLO-2 MATRIX WARF RECOVERY]				= 'CLO-2 MATRIX WARF RECOVERY'
      , [CLO-3 MATRIX WARF RECOVERY]				= 'CLO-3 MATRIX WARF RECOVERY'
      , [CLO-4 MATRIX WARF RECOVERY]				= 'CLO-4 MATRIX WARF RECOVERY'
      , [CLO-5 MATRIX WARF RECOVERY]				= 'CLO-5 MATRIX WARF RECOVERY'
      , [CLO-6 MATRIX WARF RECOVERY]				= 'CLO-6 MATRIX WARF RECOVERY'
      , [CLO-7 MATRIX WARF RECOVERY]				= 'CLO-7 MATRIX WARF RECOVERY'
	  , [SNP ASSET RECOVERY]					= 'SNP ASSET RECOVERY'
	  ,SortOrder = 1
	UNION
	SELECT 
		[LOANX] = securityCode
		,[BBG ID] = BBGId
		,[ISSUER] = issuer
		,[FACILITY] = facility
		,[LIEN TYPE] = lienType
		,[TOTAL EXPO] = cast(TotalPar as varchar(100))
		,[CLO-1] = clO1Exposure
		,[CLO-1 %] = clO1PctExposure
		,[CLO-2] = clO2Exposure
		,[CLO-2 %] = clO2PctExposure
		,[CLO-3] = clO3Exposure
		,[CLO-3 %] = clO3PctExposure
		,[CLO-4] = clO4Exposure
		,[CLO-4 %] = clO4PctExposure
		,[CLO-5] = clO5Exposure
		,[CLO-5 %] = clO5PctExposure
		,[CLO-6] = clO6Exposure
		,[CLO-6 %] = clO6PctExposure
		,[CLO-7] = clO7Exposure
		,[CLO-7 %] = clO7PctExposure
		,[CALL DATE] = callDate
		,[BID] = bid
		,[OFFER] = offer
		,[SPREAD] = cast(Spread as varchar(10))
		,[FLOOR] = cast(LiborFloor as varchar(10))
		,[MOODY'S CFR] = moodyCashFlowRating
		,[MOODY'S CFR ADJ] = moodyCashFlowRatingAdjusted
		,[MOODY FACILITY] = moodyFacilityRating
		,[MOODY FACILITY ADJ] = moodyFacilityRatingAdjusted
		,[MOODY OUTLOOK] = ap.moodyOutlook
		,[MOODY WATCH] = ap.moodyWatch
		,[WARF] = cast(WARF as varchar(10))
		,[MOODY'S RECOVERY] = cast(ap.MoodyRecovery as varchar(10))
		,[WARF RECOVERY] = cast(WARFRecovery as varchar(10))
		,[S&P ISSUER] = snPIssuerRating
		,[S&P ISSUER ADJ] = snPIssuerRatingAdjusted
		,[S&P FACILITY RATING] = snPFacilityRating
		,[S&P WATCH] = ap.snPWatch
		,[MATURITY] = maturityDate
		,[COUNTRY] = countryDesc
		,[FLOAT / FIXED] = isFloating
		,[MOODY INDUSTRY] = moodyIndustry
		,[S&P INDUSTRY] = snpIndustry
		,[COV LITE (Y/N)] = CASE	when IsCovLite = 1 then 'Y'
									when IsCovLite = 0 then 'N' 
									else null
							END
		,[CLO ANALYST] = cloAnalyst
		,[OFFER YIELD] = cast(YieldOffer as varchar(10))
		,[TARGET OFFER YIELD] = cast(targetYieldOffer as varchar(10))
		,[OFFER YIELD B/W] = cast(betterWorseOffer as varchar(10))
		,[CAPPED OFFER YIELD] = cast([CappedYieldOffer] as varchar(10))
		,[BID YIELD]  = cast([YieldBid] as varchar(10))
		,[TARGET BID YIELD] = cast(TargetYieldBid as varchar(10))
		,[CAPPED BID YIELD] = cast([CappedYieldBid] as varchar(10))
		
		,[BID YIELD B/W] = cast(BetterWorseBid as varchar(10))
		
		,[MID YIELD] = cast([YieldMid] as varchar(10))
		,[CAPPED MID YIELD] = cast([CappedYieldMid] as varchar(10))
		
		,[MID YIELD B/W] =cast(BetterWorseMid as varchar(10))
		
		,[AS OF DATE] = asOfDate
		,[1L LEVERAGE] = cast(SeniorLeverage as varchar(1000))
		,[TOTAL LEVERAGE] = totalLeverage
		,[EV MULTIPLE] = cast(EnterpriseValue as varchar(1000))
		,[LTM REVENUES] = ltmRevenues
		,[LTM EBITDA] = ltmebitda
		,[LTMFCF] = CAST(LTMFCF as VARCHAR(50))
		,[AGENT BANK] = ap.agentBank
		,[BUSINESS DESCRPTION] = cast(BusinessDescription as varchar(8000))
		,[CREDIT SCORE] = cast(CreditScore as varchar(10))
		,[NEXT REPORTING] = ap.nextReportingDate
		,[FISCAL YEAR END] = ap.fiscalYearEndDate
		,[HF ANALYST] = hfAnalyst
		,[COMMENTS] = comments		
		,CAST(cs.[CLO-6] AS VARCHAR(100)) [CLO-6 CostPrice]
		,CAST(cs.[CLO-7] AS VARCHAR(100)) [CLO-7 CostPrice]
        ,CAST([CLO1MatrixImpliedSpread]				as varchar(50))
        ,CAST([CLO2MATRIXIMPLIEDSPREAD]				as varchar(50))
        ,CAST([CLO3MATRIXIMPLIEDSPREAD]				as varchar(50))
        ,CAST([CLO4MATRIXIMPLIEDSPREAD]				as varchar(50))
        ,CAST([CLO5MATRIXIMPLIEDSPREAD]				as varchar(50))
        ,CAST([CLO6MATRIXIMPLIEDSPREAD]				as varchar(50))
        ,CAST([CLO7MATRIXIMPLIEDSPREAD]				as varchar(50))
        ,CAST([CLO1DIFFERENTIALIMPLIEDSPread]		as varchar(50))
        ,CAST([CLO2DIFFERENTIALIMPLIEDSPread]		as varchar(50))
        ,CAST([CLO3DIFFERENTIALIMPLIEDSPread]		as varchar(50))
        ,CAST([CLO4DIFFERENTIALIMPLIEDSPread]		as varchar(50))
        ,CAST([CLO5DIFFERENTIALIMPLIEDSPread]		as varchar(50))
        ,CAST([CLO6DIFFERENTIALIMPLIEDSPread]		as varchar(50))
        ,CAST([CLO7DIFFERENTIALIMPLIEDSPread] 		as varchar(50))
	    ,CAST([CLO1MATRIXWARFRECOVERY]				as varchar(50))
        ,CAST([CLO2MATRIXWARFRECOVERY]				as varchar(50))
        ,CAST([CLO3MATRIXWARFRECOVERY]				as varchar(50))
        ,CAST([CLO4MATRIXWARFRECOVERY]				as varchar(50))
        ,CAST([CLO5MATRIXWARFRECOVERY]				as varchar(50))
        ,CAST([CLO6MATRIXWARFRECOVERY]				as varchar(50))
        ,CAST([CLO7MATRIXWARFRECOVERY]				AS VARCHAR(50))
		,[SNP ASSET RECOVERY] = ap.zSnPAssetRecoveryRating
		,SortOrder = 2

	FROM [CLO].[vw_AggregatePosition] ap
	LEFT JOIN [CLO].[vw_PivotedCostPrice] cs ON ap.SecurityId = cs.SecurityId AND cs.DateId = CLO.GetPrevDayDateId()
	where  (ISNULL(@OnlyWithExposures,'NO') = 'NO' OR ISNULL(BODTotalPar,0) <> 0)



	declare @rows int = (Select count(*) from #Results)
	update #Results set
		[LOANX] = '=YDS("CloGetAllAggPositions","' + @OnlyWithExposures + '")'
		,[BBG ID] = '93=' + cast(@rows as varchar(100)) 
	where SortOrder= 0
	

	 
	declare @CacheKey varchar(1000) = 'CloGetAllAggPositions_' + @OnlyWithExposures 
	
	Update [Yoda].[YDA].[CacheLog] set
		IsCacheExpired = 1
	where 
		CacheKey = @CacheKey
		and IsCacheExpired = 0
		and [FunctId] = 6
		and [CacheLocation] = @cachelocation
		
	INSERT INTO [Yoda].[YDA].[CacheLog]
           ([FunctId]
           ,[CacheKey]
           ,[CacheDate]
           ,[RowCount]
           ,Param1
           ,[CacheLocation])
     VALUES
           (6
           ,@CacheKey
           ,getdate()
           ,@rows
           ,@OnlyWithExposures
           ,@cachelocation)

	SELECT 
		[LOANX]
		,[BBG ID]
		,[ISSUER]
		,[FACILITY]
		,[LIEN TYPE]
		,[TOTAL EXPO]
		,[CLO-1]
		,[CLO-1 %]
		,[CLO-2]
		,[CLO-2 %]
		,[CLO-3]
		,[CLO-3 %]
		,[CLO-4]
		,[CLO-4 %]
		,[CLO-5]
		,[CLO-5 %]
		,[CLO-6]
		,[CLO-6 %]
		,[CLO-7]
		,[CLO-7 %]
		,[CALL DATE]
		,[BID]
		,[OFFER]
		,[SPREAD]
		,[FLOOR]
		,[MOODY'S CFR]
		,[MOODY'S CFR ADJ]
		,[MOODY FACILITY]
		,[MOODY FACILITY ADJ]
		,[MOODY OUTLOOK]
		,[MOODY WATCH]
		,[WARF]
		,[MOODY'S RECOVERY]
		,[WARF RECOVERY]
		,[S&P ISSUER]
		,[S&P ISSUER ADJ]
		,[S&P FACILITY RATING]
		,[S&P WATCH]
		,[MATURITY]
		,[COUNTRY]
		,[FLOAT / FIXED]
		,[MOODY INDUSTRY]
		,[S&P INDUSTRY]
		,[COV LITE (Y/N)]
		,[CLO ANALYST]
		,[OFFER YIELD]
		,[TARGET OFFER YIELD]
		,[OFFER YIELD B/W]
		,[CAPPED OFFER YIELD]
		,[BID YIELD]
		,[TARGET BID YIELD]
		,[CAPPED BID YIELD]
		
		,[BID YIELD B/W]
		
		,[MID YIELD]
		,[CAPPED MID YIELD]
		
		,[MID YIELD B/W]
		
		,[AS OF DATE]
		,[1L LEVERAGE]
		,[TOTAL LEVERAGE]
		,[EV MULTIPLE]
		,[LTM REVENUES]
		,[LTM EBITDA]
		,[LTMFCF]
		,[AGENT BANK]
		,[BUSINESS DESCRPTION]
		,[CREDIT SCORE]
		,[NEXT REPORTING]
		,[FISCAL YEAR END]
		,[HF ANALYST]
		,[COMMENTS]
		,[CLO-6 COST PRICE]
		,[CLO-7 COST PRICE]
	    ,[CLO-1 MATRIX IMPLIED SPREAD]		
	    ,[CLO-2 MATRIX IMPLIED SPREAD]		
	    ,[CLO-3 MATRIX IMPLIED SPREAD]		
	    ,[CLO-4 MATRIX IMPLIED SPREAD]		
	    ,[CLO-5 MATRIX IMPLIED SPREAD]		
	    ,[CLO-6 MATRIX IMPLIED SPREAD]		
	    ,[CLO-7 MATRIX IMPLIED SPREAD]		
	    ,[CLO-1 DIFFERENTIAL IMPLIED SPREAD]
	    ,[CLO-2 DIFFERENTIAL IMPLIED SPREAD]
	    ,[CLO-3 DIFFERENTIAL IMPLIED SPREAD]
	    ,[CLO-4 DIFFERENTIAL IMPLIED SPREAD]
	    ,[CLO-5 DIFFERENTIAL IMPLIED SPREAD]
	    ,[CLO-6 DIFFERENTIAL IMPLIED SPREAD]
	    ,[CLO-7 DIFFERENTIAL IMPLIED SPREAD]
	    ,[CLO-1 MATRIX WARF RECOVERY]		
	    ,[CLO-2 MATRIX WARF RECOVERY]		
	    ,[CLO-3 MATRIX WARF RECOVERY]		
	    ,[CLO-4 MATRIX WARF RECOVERY]		
	    ,[CLO-5 MATRIX WARF RECOVERY]		
	    ,[CLO-6 MATRIX WARF RECOVERY]		
	    ,[CLO-7 MATRIX WARF RECOVERY]		
		,[SNP ASSET RECOVERY]
	 FROM #results 
	 ORDER BY sortorder

 DROP TABLE #results

RETURN 0
GO

PRINT N'Update complete.';


GO
INSERT INTO clo.Field
(
    FieldGroupId,
    FieldName,
    JsonPropertyName,
    FieldTitle,
    JsonFormatString,
    DisplayWidth,
    IsPercentage,
    SortOrder,
    FieldType,
    HeaderCellClass,
    CellClass,
    CellTemplate,
    Hidden,
    PinnedLeft,
    IsSecurityOverride,
    ShowInFilter,
    FilterOrder
)
VALUES
( 2, 'zSnPAssetRecoveryRating', 'zSnPAssetRecoveryRating', 'S&P ASSET RECOVERY', '', 120, 0, 140.0000, 1, NULL, NULL, NULL, NULL, NULL, NULL, 1, 700.00 )
GO
INSERT INTO [CLO].[CustomViewField]
           ([ViewId]
           ,[FieldId]
           ,[SortOrder]
           ,[IsPinned])
     VALUES
           (1
           ,174
           ,755
           ,0)
GO

UPDATE	CLO.Field 
SET FieldTitle = 'MOODY''S RECOVERY',
DisplayWidth = 120
WHERE FieldId = 17

GO

