using System;

namespace YCM.CLO.DataAccess.Models
{
	public partial class vw_Position
    {
        public long? PositionId { get; set; }
        public int? PositionDateId { get; set; }
        public string Exposure { get; set; }
        public decimal? NumExposure { get; set; }
        public decimal BODExposure { get; set; }
        public decimal? BODwithBuyExposure { get; set; }
        public string PctExposure { get; set; }
        public decimal? PxPrice { get; set; }
        public decimal? PctExposureNum { get; set; }
        public int? FundId { get; set; }
        public string FundCode { get; set; }
        public string FundDesc { get; set; }
        public int? SecurityId { get; set; }
        public string SecurityCode { get; set; }
        public string SecurityDesc { get; set; }
        public string BBGId { get; set; }
        public string Issuer { get; set; }
        public string IssuerDesc { get; set; }
        public int? IssuerId { get; set; }
        public string Facility { get; set; }
        public string CallDate { get; set; }
        public string CountryDesc { get; set; }
        public string MaturityDate { get; set; }
        public string SnpIndustry { get; set; }
        public string MoodyIndustry { get; set; }
        public string IsCovLite { get; set; }
        public string IsFloating { get; set; }
        public string LienType { get; set; }
        public bool? IsOnWatch { get; set; }
        public short? WatchObjectTypeId { get; set; }
        public int? WatchObjectId { get; set; }
        public int? WatchId { get; set; }
        public string WatchComments { get; set; }
        public string WatchLastUpdatedOn { get; set; }
        public string WatchUser { get; set; }
	    public bool IsSellCandidate => SellCandidateId.GetValueOrDefault() > 0;
	    public short? SellCandidateObjectTypeId { get; set; }
	    public int? SellCandidateObjectId { get; set; }
	    public int? SellCandidateId { get; set; }
	    public string SellCandidateComments { get; set; }
	    public string SellCandidateLastUpdatedOn { get; set; }
	    public string SellCandidateUser { get; set; }
        public string OrigSecurityCode { get; set; }
        public string OrigSecurityDesc { get; set; }
        public string OrigBBGId { get; set; }
        public string OrigIssuer { get; set; }
        public string OrigFacility { get; set; }
        public string OrigCallDate { get; set; }
        public string OrigMaturityDate { get; set; }
        public string OrigSnpIndustry { get; set; }
        public string OrigMoodyIndustry { get; set; }
        public string OrigIsFloating { get; set; }
        public string OrigLienType { get; set; }
        public string OrigMoodyFacilityRatingAdjusted { get; set; }
        public string OrigMoodyCashFlowRatingAdjusted { get; set; }
        public decimal? PrincipalCash { get; set; }
        public decimal? LiabilityPar { get; set; }
        public decimal? EquityPar { get; set; }
        public short? MoodyIndustryId { get; set; }
        public DateTime? SecurityLastUpdatedOn { get; set; }
        public string SecurityLastUpdatedBy { get; set; }
        public DateTime? SecurityCreatedOn { get; set; }
        public string SecurityCreatedBy { get; set; }
        public int? MarketDateId { get; set; }
        public long? MarketDataId { get; set; }
        public int? OverrideMarketDataId { get; set; }
        public string Bid { get; set; }
        public string Offer { get; set; }
        public string PrevDayBid { get; set; }
        public string PrevDayOffer { get; set; }
        public string CostPrice { get; set; }
        public decimal? CostPriceNum { get; set; }
        public decimal? BidNum { get; set; }
        public decimal? OfferNum { get; set; }
        public string PctBidDiff { get; set; }
        public decimal? PctBidDiffNum { get; set; }
        public string PctOfferDiff { get; set; }
        public decimal? PctOfferDiffNum { get; set; }
        public decimal? PriceMove { get; set; }
        public decimal? PrevDayBidNum { get; set; }
        public decimal? PrevDayOfferNum { get; set; }
        public decimal? Spread { get; set; }
        public decimal? LiborFloor { get; set; }
        public string MoodyCashFlowRating { get; set; }
        public string MoodyCashFlowRatingAdjusted { get; set; }
        public string MoodyFacilityRating { get; set; }
        public decimal? MoodyRecovery { get; set; }
        public string SnPIssuerRating { get; set; }
        public string SnPIssuerRatingAdjusted { get; set; }
        public string SnPFacilityRating { get; set; }
        public string SnPfacilityRatingAdjusted { get; set; }
        public string SnPRecoveryRating { get; set; }
        public string MoodyOutlook { get; set; }
        public string MoodyWatch { get; set; }
        public string SnPWatch { get; set; }
        public string NextReportingDate { get; set; }
        public string FiscalYearEndDate { get; set; }
        public string AgentBank { get; set; }
        public int? CalculationId { get; set; }
        public decimal? YieldBid { get; set; }
        public decimal? YieldOffer { get; set; }
        public decimal? YieldMid { get; set; }
        public decimal? CappedYieldBid { get; set; }
        public decimal? CappedYieldOffer { get; set; }
        public decimal? CappedYieldMid { get; set; }
        public decimal? TargetYieldBid { get; set; }
        public decimal? TargetYieldOffer { get; set; }
        public decimal? TargetYieldMid { get; set; }
        public decimal? BetterWorseBid { get; set; }
        public decimal? BetterWorseOffer { get; set; }
        public decimal? BetterWorseMid { get; set; }
        public decimal? TotalCoupon { get; set; }
        public decimal? WARF { get; set; }
        public decimal? WARFRecovery { get; set; }
        public decimal? Life { get; set; }
        public int? CalculationDateId { get; set; }
        public string TotalPar { get; set; }
        public decimal? TotalParNum { get; set; }
        public decimal BODTotalPar { get; set; }
        public string MoodyFacilityRatingAdjusted { get; set; }
        public int? AnalystResearchId { get; set; }
        public string CLOAnalyst { get; set; }
        public string HFAnalyst { get; set; }
        public string AsOfDate { get; set; }
        public decimal? CreditScore { get; set; }
        public decimal? LiquidityScore { get; set; }
        public decimal? OneLLeverage { get; set; }
        public string TotalLeverage { get; set; }
        public string EVMultiple { get; set; }
        public string LTMRevenues { get; set; }
        public string LTMEBITDA { get; set; }
        public string FCF { get; set; }
        public string Comments { get; set; }
        public string BusinessDescription { get; set; }
        public short? MoodyCashFlowRatingAdjustedRank { get; set; }
        public short? MoodyFacilityRatingAdjustedRank { get; set; }
        public DateTime? SecurityMaturityDate { get; set; }
        public int? MaturityDays { get; set; }
        public decimal? WALifeAdjustment { get; set; }
        public bool? IsOnAlert { get; set; }
        public int? SearchText { get; set; }
	    public decimal? SeniorLeverage { get; set; }
	    public decimal? EnterpriseValue { get; set; }
	    public decimal? LTMFCF { get; set; }
		//public bool? IsPrivate { get; set; }
	    public string Sponsor { get; set; }

        public decimal? MatrixImpliedSpread { get; set; }

        public decimal? DifferentialSpread { get; set; }

        public string LiborCategory { get; set; }

        public string LiborTransitionNote { get; set; }


    }
}
