using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace YCM.CLO.DataAccess.Models
{
	public partial class WSOExtractAsset
    {
        public int ExtractAssetKey { get; set; }
        public int DatasetKey { get; set; }
        public int DateId { get; set; }
        public string AssetId { get; set; }
        public string Asset { get; set; }
        public decimal? ABSAverageLifeCollateralDescriptor { get; set; }
        public string ABSCategory { get; set; }
        public decimal? ABSCurrentFactor { get; set; }
        public int? ABSSpecificCode { get; set; }
        public string ABSType { get; set; }
        public decimal? AccretedValue { get; set; }
        public decimal? AccretionFactor { get; set; }
        public decimal? AccruedFees { get; set; }
        public decimal? AccruedInterest { get; set; }
        public decimal? AggregateAmortCost { get; set; }
        public string AssetCategoryMoody { get; set; }
        public string AssetCategorySP { get; set; }
        public string AssetType { get; set; }
        public string AttachedEquity { get; set; }
        public decimal? AvgLife { get; set; }
        public decimal? CalculationAmount { get; set; }
        public decimal? CalculationAmount2 { get; set; }
        public decimal? CalculationAmount3 { get; set; }
        public int? CalendarID { get; set; }
        public DateTime? CallDate { get; set; }
        public decimal? CapitalizedInterest { get; set; }
        public string ConvertibleType { get; set; }
        public decimal? Convexity { get; set; }
        public string CostBasis { get; set; }
        public decimal? CostPrice { get; set; }
        public string CountryOfOperation { get; set; }
        public string CouponType { get; set; }
        public decimal? CreditLinkedAmount { get; set; }
        public string CreditLinkedCounterInstitution { get; set; }
        public string CurrencyOther { get; set; }
        public int? CurrencyTypeID { get; set; }
        public decimal? CurrentYield { get; set; }
        public decimal? CurrentYTM { get; set; }
        public decimal? CurrentYTW { get; set; }
        public string CUSIP { get; set; }
        public int? DateOffset { get; set; }
        public int? DayCount { get; set; }
        public DateTime? DefaultDate { get; set; }
        public decimal? DefaultProbabilityMoody { get; set; }
        public string DefaultType { get; set; }
        public string Description { get; set; }
        public decimal? EarnedInterest { get; set; }
        public string EmergingMarketRegion { get; set; }
        public decimal? ExclusionAmountMoody { get; set; }
        public decimal? ExclusionAmountSP { get; set; }
        public decimal? ExpectedLossMoody { get; set; }
        public string FacilityType { get; set; }
        public DateTime? FirstPaymentDate { get; set; }
        public DateTime? FirstSettleDate { get; set; }
        public decimal? FixedRate { get; set; }
        public int? Frequency { get; set; }
        public string Guarantor { get; set; }
        public string Insurer { get; set; }
        public DateTime? InterestAccrualDate { get; set; }
        public decimal? InterestAndFeesProjected { get; set; }
        public decimal? InterestAndFeesProjectedForNextPeriod { get; set; }
        public decimal? InterestAndFeesToDate { get; set; }
        public decimal? InterestAndFeesToDateForNextPeriod { get; set; }
        public bool? IsABS { get; set; }
        public bool IsBankruptcyRelated { get; set; }
        public bool IsBridgeSecurity { get; set; }
        public bool? IsCallable { get; set; }
        public bool IsConflictOfInterest { get; set; }
        public bool IsConvertible { get; set; }
        public bool IsCreditAvailable { get; set; }
        public bool IsCreditDefaultSwap { get; set; }
        public bool IsCurrentPay { get; set; }
        public bool IsDeepDiscount { get; set; }
        public bool IsDefeased { get; set; }
        public bool IsDeferredInterestOutstanding { get; set; }
        public bool IsDeferredInterestAllowed { get; set; }
        public bool IsDerivative { get; set; }
        public bool IsDIP { get; set; }
        public bool IsEligibleInvestment { get; set; }
        public bool IsEmergingMarket { get; set; }
        public bool? IsEnhancedBond { get; set; }
        public bool IsEstimatedRatingFitch { get; set; }
        public bool IsEstimatedRatingMoody { get; set; }
        public bool IsEstimatedRatingSP { get; set; }
        public bool IsException { get; set; }
        public bool IsFXRisk { get; set; }
        public bool IsGovtSponsored { get; set; }
        public bool? IsGuaranteed { get; set; }
        public bool IsHedged { get; set; }
        public string ISIN { get; set; }
        public bool IsInDefault { get; set; }
        public bool? IsIO { get; set; }
        public bool IsLBOFund { get; set; }
        public bool IsLBR6MOAgent { get; set; }
        public bool IsLBR6MOMajor { get; set; }
        public bool IsLBR6MOSuper { get; set; }
        public bool IsLeaseFinancingTransaction { get; set; }
        public bool IsMezzanine { get; set; }
        public bool? IsMostSenior { get; set; }
        public bool IsOffer { get; set; }
        public bool IsOriginal { get; set; }
        public bool IsPIKSecurity { get; set; }
        public bool? IsPO { get; set; }
        public bool IsPreferredSecurity { get; set; }
        public bool IsRatingFitchDerived { get; set; }
        public bool IsRatingMoodyDerived { get; set; }
        public bool IsRatingSPDerived { get; set; }
        public bool IsResecuritization { get; set; }
        public bool? IsRestructured { get; set; }
        public bool IsSFO { get; set; }
        public bool IsSovereign { get; set; }
        public bool IsSpecialSituation { get; set; }
        public bool IsSPVJurisdiction { get; set; }
        public string Issuer { get; set; }
        public DateTime? IssueDate { get; set; }
        public decimal? IssueSize { get; set; }
        public string IssuingTransaction { get; set; }
        public bool IsSynthetic { get; set; }
        public bool IsSyntheticCounterInstitutionInDefault { get; set; }
        public bool IsTaxJurisdiction { get; set; }
        public decimal? LCAmount { get; set; }
        public string LeadUnderwriter { get; set; }
        public bool LiborOptionExists { get; set; }
        public string LienType { get; set; }
        public string Liquidity { get; set; }
        public decimal? LongDatedAmount { get; set; }
        public decimal? LossRateMoody { get; set; }
        public decimal? LossSeverityMoody { get; set; }
        public decimal? MacaulayDuration { get; set; }
        public DateTime? MarkDate { get; set; }
        public decimal? MarketValue { get; set; }
        public decimal? MarketValueAdjustedMoody { get; set; }
        public decimal? MarketValueAdjustedSP { get; set; }
        public decimal? MarketValueOCMoody { get; set; }
        public decimal? MarketValueOCSP { get; set; }
        public decimal? MarketValueSettleTrue { get; set; }
        public int? MarkFactor { get; set; }
        public decimal? MarkPrice { get; set; }
        public DateTime? MaturityDate { get; set; }
        public string MaturityExceptions { get; set; }
        public decimal? ModDuration { get; set; }
        public DateTime? NextPaymentDate { get; set; }
        public decimal? OriginalCapPercent { get; set; }
        public decimal? OriginalPAPI { get; set; }
        public decimal? Outstanding { get; set; }
        public decimal? OutstandingAdjusted { get; set; }
        public decimal? PAI { get; set; }
        public decimal? ParAmount { get; set; }
        public decimal? ParAmountTraded { get; set; }
        public int? PaymentNonBusinessDirection { get; set; }
        public int? PaymentOffsetDays { get; set; }
        public int? PaymentOffsetDirection { get; set; }
        public int? PaymentOffsetType { get; set; }
        public DateTime? PIKBeginDate { get; set; }
        public decimal? PIKCapInterest { get; set; }
        public decimal? PIKMargin { get; set; }
        public decimal? PIKPercentage { get; set; }
        public bool PrimeOptionExists { get; set; }
        public decimal? PrincipalBalance { get; set; }
        public decimal? PrincipalBalanceEI { get; set; }
        public int? PriorityCategoryFitch { get; set; }
        public int? PriorityCategoryMoody { get; set; }
        public int? PriorityCategorySP { get; set; }
        public DateTime? PutDate { get; set; }
        public decimal? Quantity { get; set; }
        public int? RateAdjustFreq { get; set; }
        public string RateOption { get; set; }
        public string RatingMoody { get; set; }
        public string RatingMoodyAtIssuance { get; set; }
        public string RatingMoodyDerived { get; set; }
        public string RatingMoodyIssuance { get; set; }
        public string RatingMoodySecurity { get; set; }
        public string RatingMoodyShort { get; set; }
        public string RatingFitch { get; set; }
        public string RatingFitchAtIssuance { get; set; }
        public string RatingFitchDerived { get; set; }
        public string RatingFitchSecurity { get; set; }
        public string RatingSP { get; set; }
        public string RatingSPAtIssuance { get; set; }
        public string RatingSPDerived { get; set; }
        public string RatingSPSecurity { get; set; }
        public string RatingSPShort { get; set; }
        public string RatingDCR { get; set; }
        public string RatingDCRDerived { get; set; }
        public string Region { get; set; }
        public decimal? RecoveryRateFitch { get; set; }
        public decimal? RecoveryRateMoody { get; set; }
        public decimal? RecoveryRateSP { get; set; }
        public string ReferenceAssetID { get; set; }
        public string RegistrationType { get; set; }
        public string SecurityID { get; set; }
        public string SecurityLevel { get; set; }
        public string SecurityLevelFitch { get; set; }
        public string SecurityLevelMoody { get; set; }
        public string SecurityLevelSP { get; set; }
        public decimal? SelfPurchasedAmount { get; set; }
        public string Servicer { get; set; }
        public string SFOType { get; set; }
        public decimal? SpreadLibor { get; set; }
        public decimal? SpreadPrime { get; set; }
        public decimal? StdDevMoody { get; set; }
        public string SyntheticCounterInstitution { get; set; }
        public string SyntheticType { get; set; }
        public bool? TradesWithAccrued { get; set; }
        public string TransferAgent { get; set; }
        public string UpgradedDowngraded { get; set; }
        public decimal? WeightedAvgAllInRate { get; set; }
        public decimal? WeightedAvgSpread { get; set; }
        public decimal? WeightedAvgDaysToReset { get; set; }
        public decimal? WeightedAvgDaysToResetAmount { get; set; }
        public decimal? YieldToWorst { get; set; }
        public decimal? YTM { get; set; }
        public decimal? YTW { get; set; }
        public decimal? UserAmount1 { get; set; }
        public decimal? UserAmount2 { get; set; }
        public decimal? UserAmount3 { get; set; }
        public decimal? UserAmount4 { get; set; }
        public decimal? UserAmount5 { get; set; }
        public decimal? UserAmount6 { get; set; }
        public decimal? UserAmount7 { get; set; }
        public decimal? UserAmount8 { get; set; }
        public decimal? UserAmount9 { get; set; }
        public decimal? UserAmount10 { get; set; }
        public decimal? UserAmount11 { get; set; }
        public decimal? UserAmount12 { get; set; }
        public decimal? UserAmount13 { get; set; }
        public decimal? UserAmount14 { get; set; }
        public decimal? UserAmount15 { get; set; }
        public decimal? UserAmount16 { get; set; }
        public decimal? UserAmount17 { get; set; }
        public decimal? UserAmount18 { get; set; }
        public decimal? UserAmount19 { get; set; }
        public decimal? UserAmount20 { get; set; }
        public bool? Is_Second_Lien { get; set; }
        public bool? UserFlag2 { get; set; }
        public bool? Is_First_Lien { get; set; }
        public bool? UserFlag4 { get; set; }
        public bool? Is_Current_Pay_as_Default { get; set; }
        public bool? UserFlag6 { get; set; }
        public bool? UserFlag7 { get; set; }
        public bool? UserFlag8 { get; set; }
        public bool? Is_Covenant_Pari_Passu { get; set; }
        public bool? Is_Moody_Senior_Secured_Loan { get; set; }
        public bool? Is_Purchased_Discount { get; set; }
        public bool? UserFlag12 { get; set; }
        public bool? UserFlag13 { get; set; }
        public bool? Is_Cov_Lite { get; set; }
        public bool? Is_Moody_s_DP_Rating_Derived { get; set; }
        public bool? UserFlag16 { get; set; }
        public bool? UserFlag17 { get; set; }
        public bool? UserFlag18 { get; set; }
        public bool? UserFlag19 { get; set; }
        public bool? UserFlag20 { get; set; }
        public string zIs_Floor_in_Effect { get; set; }
        public string Counterparty_Type { get; set; }
        public string OC_Recovery_Type { get; set; }
        public string Moody_s_DP_Rating___WARF__ADJ_ { get; set; }
        public string Moody_s_CF_Rating { get; set; }
        public string Moody_s_DP_Rating___WARF { get; set; }
        public string S_P_Issuer_Rating { get; set; }

        public string Moody_s_DP_Rating__Unnotched____WARF { get; set; }
        public string Moody_s_Credit_Watch { get; set; }
        public string Issuer_Name_Alternative { get; set; }
        public string Issuer_Country { get; set; }
        public string SIC_Moody { get; set; }
        public string SIC_S_P { get; set; }
        public string Moody_s_Outlook { get; set; }
        public string S_P_Credit_Watch { get; set; }
        public string WAL_Date_GV__Hidden_ { get; set; }
        public double? Adjusted_WAS { get; set; }
        public double? Adjusted_WAC { get; set; }
        public double? All_In_Rate__w_Floor_ { get; set; }
        public double? LIBOR_Floor_for_accrual_WAS { get; set; }
        public double? LIBOR_Floor_Credit_Addback { get; set; }
        public double? LIBOR_Base_Rate_on_Notes { get; set; }
        public decimal? Cost_Price_Discounts { get; set; }
        public decimal? Cost_Price__Discounts_ { get; set; }
        public decimal? UserDecimal3 { get; set; }
        public decimal? UserDecimal4 { get; set; }
        public decimal? UserDecimal5 { get; set; }
        public int? WAL_Date_Case__Hidden_ { get; set; }
        public int? UserNumber2 { get; set; }
        public int? UserNumber3 { get; set; }
        public int? UserNumber4 { get; set; }
        public int? UserNumber5 { get; set; }
        public DateTime? UserDate1 { get; set; }
        public DateTime? UserDate2 { get; set; }
        public DateTime? UserDate3 { get; set; }
        public DateTime? UserDate4 { get; set; }
        public DateTime? UserDate5 { get; set; }
        public decimal? FacilityIncrease { get; set; }
        public decimal? ParAmountNativeHypo { get; set; }
        public decimal? OutstandingNativeHypo { get; set; }
        public decimal? BankDeal_GlobalAmount { get; set; }
        public decimal? ExcessCurrentPay { get; set; }
        public decimal? ExcessMoodyCaa { get; set; }
        public decimal? ExcessSPCCC { get; set; }
        public decimal? FeeSpread { get; set; }
        public decimal? InterestFromReinvestment { get; set; }
        public bool? IsDelayedDraw { get; set; }
        public bool? IsRatingMoodyPending { get; set; }
        public decimal? LiborBaseRateFloor { get; set; }
        public decimal? MarkPrice_BidPrice { get; set; }
        public DateTime? PaymentDate { get; set; }
        public decimal? PrimarySpread { get; set; }
        public string PrimarySpreadType { get; set; }
        public decimal? PrimeBaseRateFloor { get; set; }
        public int? PriorityCategorySPI { get; set; }
        public int? PriorityCategorySPII { get; set; }
        public int? PriorityCategorySPIII { get; set; }
        public int? PriorityCategorySPIV { get; set; }
        public int? PriorityCategorySPV { get; set; }
        public int? PriorityCategorySPVI { get; set; }
        public bool? RatingMoodyIsShadow { get; set; }
        public string RatingMoodyIssue { get; set; }
        public string RatingSPIssue { get; set; }
        public string RatingSPIssueCreditWatch { get; set; }
        public decimal? RecoveryAmountCurrentPay { get; set; }
        public decimal? RecoveryAmountMoodyCaa { get; set; }
        public decimal? RecoveryAmountSPCCC { get; set; }
        public decimal? RecoveryRateMoodyFeed { get; set; }
        public decimal? RecoveryRateSPI { get; set; }
        public decimal? RecoveryRateSPII { get; set; }
        public decimal? RecoveryRateSPIII { get; set; }
        public decimal? RecoveryRateSPIV { get; set; }
        public decimal? RecoveryRateSPV { get; set; }
        public decimal? RecoveryRateSPVI { get; set; }
        public string CoreSystem { get; set; }
        public bool? RecordModified { get; set; }
        public short? Scenario { get; set; }
        public decimal? MarkPrice_AskPrice { get; set; }
        public string RatingMoodyIssueCreditWatch { get; set; }
    }
}
