CREATE SCHEMA [CLO]
GO

--GRANT VIEW DEFINITION,SELECT,EXECUTE,INSERT,UPDATE,DELETE,ALTER ON SCHEMA::[CLO] TO [YORK\svcyoda]
--GO

--GRANT VIEW DEFINITION,SELECT,EXECUTE,INSERT,UPDATE,DELETE,ALTER ON SCHEMA::[CLO] TO [YODAUSER]
--GO

--GRANT VIEW DEFINITION,SELECT,EXECUTE,INSERT,UPDATE,DELETE,ALTER ON SCHEMA::[CLO] TO [YORK\Developers Group]
--GO

--GRANT VIEW DEFINITION,SELECT,EXECUTE,INSERT,UPDATE,DELETE,ALTER ON SCHEMA::[CLO] to yorkuser
--GO

--GRANT VIEW DEFINITION,SELECT,EXECUTE,INSERT,UPDATE,DELETE,ALTER ON SCHEMA::[CLO] to YCG_reportreader
--GO

--GRANT VIEW DEFINITION,SELECT,EXECUTE,INSERT,UPDATE,DELETE,ALTER ON SCHEMA::[CLO] to [YORK\App - OpsExcel]
--GO

--GRANT VIEW DEFINITION,SELECT,EXECUTE,INSERT,UPDATE,DELETE,ALTER ON SCHEMA::[CLO] to [YORK\App - TreasuryExcel]
--GO

--GRANT VIEW DEFINITION,SELECT,EXECUTE,INSERT,UPDATE,DELETE,ALTER ON SCHEMA::[CLO] to [YORK\Developers Group]
--GO

--GRANT VIEW DEFINITION,SELECT,EXECUTE,INSERT,UPDATE,DELETE,ALTER ON SCHEMA::[CLO] to [YORK\App - ValuationExcel]
--GO


